// Glossary data - 200+ DevOps terms
export const glossaryData = [
  // === CI/CD (25 terms) ===
  { id: 'ci', term: 'CI (Continuous Integration)', definition: 'Pratique consistant à intégrer fréquemment le code dans un dépôt partagé, avec vérification automatique par build et tests.', relatedCourseId: 'jenkins' },
  { id: 'cd', term: 'CD (Continuous Delivery)', definition: 'Extension de la CI qui automatise le déploiement du code en production ou environnement de staging.', relatedCourseId: 'jenkins' },
  { id: 'pipeline', term: 'Pipeline', definition: "Enchaînement automatisé d'étapes (build, test, deploy) dans un processus CI/CD.", relatedCourseId: 'jenkins' },
  { id: 'stage', term: 'Stage', definition: "Phase logique d'un pipeline CI/CD regroupant un ensemble de jobs (ex: build, test, deploy).", relatedCourseId: 'gitlab-ci' },
  { id: 'job-ci', term: 'Job (CI/CD)', definition: "Unité de travail individuelle dans un pipeline, exécutant un script ou une commande spécifique.", relatedCourseId: 'gitlab-ci' },
  { id: 'artifact', term: 'Artifact', definition: 'Fichier binaire produit par un build (JAR, WAR, Docker image, npm package).', relatedCourseId: 'artifactory' },
  { id: 'runner', term: 'Runner (GitLab CI)', definition: 'Agent qui exécute les jobs définis dans le pipeline CI/CD GitLab.', relatedCourseId: 'gitlab-ci' },
  { id: 'webhook', term: 'Webhook', definition: 'Mécanisme de callback HTTP automatique déclenché par un événement.', relatedCourseId: 'jenkins' },
  { id: 'build', term: 'Build', definition: "Processus de compilation et d'assemblage du code source en un livrable exécutable ou déployable.", relatedCourseId: 'jenkins' },
  { id: 'deploy', term: 'Deploy', definition: "Action de mettre en production ou en environnement cible une application ou un service.", relatedCourseId: 'jenkins' },
  { id: 'rollback', term: 'Rollback', definition: "Retour à une version précédente d'une application ou infrastructure en cas de problème.", relatedCourseId: 'jenkins' },
  { id: 'canary', term: 'Canary Deployment', definition: "Déploiement progressif où une nouvelle version est exposée à un petit pourcentage d'utilisateurs.", relatedCourseId: null },
  { id: 'blue-green', term: 'Blue-Green Deployment', definition: 'Stratégie de déploiement utilisant deux environnements identiques pour zéro-downtime.', relatedCourseId: null },
  { id: 'feature-flag', term: 'Feature Flag', definition: "Technique permettant d'activer ou désactiver une fonctionnalité sans redéployer le code.", relatedCourseId: null },
  { id: 'trunk-based', term: 'Trunk-Based Development', definition: "Pratique où les développeurs intègrent leur code dans une branche principale (trunk) fréquemment.", relatedCourseId: 'git-avance' },
  { id: 'git-flow', term: 'Git Flow', definition: 'Modèle de branching Git avec des branches dédiées pour features, releases et hotfixes.', relatedCourseId: 'git-avance' },
  { id: 'release', term: 'Release', definition: "Version publiée d'un logiciel, prête à être déployée en production.", relatedCourseId: 'gitlab-ci' },
  { id: 'hotfix', term: 'Hotfix', definition: "Correction urgente appliquée directement en production pour résoudre un bug critique.", relatedCourseId: 'git-avance' },
  { id: 'semver', term: 'Semantic Versioning', definition: "Convention de versionnage (MAJOR.MINOR.PATCH) indiquant la nature des changements.", relatedCourseId: null },
  { id: 'changelog', term: 'Changelog', definition: "Document listant les modifications entre chaque version d'un logiciel.", relatedCourseId: null },
  { id: 'continuous-deploy', term: 'Continuous Deployment', definition: "Extension du CD où chaque changement passant les tests est automatiquement déployé en production.", relatedCourseId: 'jenkins' },
  { id: 'pipeline-as-code', term: 'Pipeline as Code', definition: "Définition du pipeline CI/CD dans un fichier versionné (Jenkinsfile, .gitlab-ci.yml).", relatedCourseId: 'jenkins' },
  { id: 'jenkinsfile', term: 'Jenkinsfile', definition: 'Fichier Groovy décrivant un pipeline Jenkins as Code.', relatedCourseId: 'jenkins' },
  { id: 'jenkins-agent', term: 'Jenkins Agent', definition: "Machine qui exécute les tâches d'un pipeline Jenkins, dirigée par le controller.", relatedCourseId: 'jenkins' },
  { id: 'gitlab-ci-yml', term: '.gitlab-ci.yml', definition: "Fichier de configuration YAML définissant le pipeline CI/CD dans GitLab.", relatedCourseId: 'gitlab-ci' },

  // === Containers (25 terms) ===
  { id: 'container', term: 'Container', definition: "Unité standard de logiciel qui empaquète le code et ses dépendances pour une exécution fiable et reproductible.", relatedCourseId: 'docker' },
  { id: 'image', term: 'Image Docker', definition: 'Template en lecture seule contenant les instructions pour créer un container Docker.', relatedCourseId: 'docker' },
  { id: 'dockerfile', term: 'Dockerfile', definition: 'Fichier texte contenant les instructions pour construire une image Docker.', relatedCourseId: 'docker' },
  { id: 'layer', term: 'Layer (Docker)', definition: "Couche du système de fichiers en lecture seule constituant une image Docker.", relatedCourseId: 'docker' },
  { id: 'registry', term: 'Registry', definition: "Service de stockage et distribution d'images Docker (Docker Hub, Harbor, ECR).", relatedCourseId: 'docker' },
  { id: 'volume', term: 'Volume (Docker)', definition: 'Mécanisme de persistance des données pour les containers Docker.', relatedCourseId: 'docker' },
  { id: 'docker-network', term: 'Network (Docker)', definition: "Réseau virtuel permettant la communication entre containers Docker.", relatedCourseId: 'docker' },
  { id: 'bridge-network', term: 'Bridge Network', definition: "Driver réseau Docker par défaut créant un réseau privé interne sur l'hôte.", relatedCourseId: 'docker' },
  { id: 'overlay-network', term: 'Overlay Network', definition: "Réseau Docker multi-hôtes permettant la communication entre containers sur différentes machines.", relatedCourseId: 'docker' },
  { id: 'docker-compose', term: 'Docker Compose', definition: "Outil pour définir et exécuter des applications multi-containers avec un fichier YAML.", relatedCourseId: 'docker' },
  { id: 'docker-swarm', term: 'Docker Swarm', definition: "Outil natif d'orchestration Docker pour gérer un cluster de moteurs Docker.", relatedCourseId: 'docker' },
  { id: 'orchestration', term: 'Orchestration', definition: "Gestion automatisée de containers, incluant déploiement, scaling et networking.", relatedCourseId: 'kubernetes' },
  { id: 'containerd', term: 'containerd', definition: "Runtime de containers industriel gérant le cycle de vie complet des containers sur un hôte.", relatedCourseId: 'docker' },
  { id: 'oci', term: 'OCI (Open Container Initiative)', definition: "Standard ouvert définissant les spécifications pour les formats d'images et runtimes de containers.", relatedCourseId: 'docker' },
  { id: 'cgroup', term: 'cgroup', definition: "Fonctionnalité du noyau Linux limitant et isolant les ressources (CPU, mémoire) des processus.", relatedCourseId: 'docker' },
  { id: 'namespace-linux', term: 'Namespace (Linux)', definition: "Fonctionnalité du noyau Linux isolant les ressources système visibles par un groupe de processus.", relatedCourseId: 'docker' },
  { id: 'multi-stage', term: 'Multi-stage Build', definition: "Technique Dockerfile utilisant plusieurs étapes de build pour réduire la taille de l'image finale.", relatedCourseId: 'docker' },
  { id: 'scratch', term: 'Scratch (Docker)', definition: "Image Docker vide servant de base pour créer des images minimales sans système d'exploitation.", relatedCourseId: 'docker' },
  { id: 'alpine', term: 'Alpine Linux', definition: "Distribution Linux ultra-légère (~5MB) souvent utilisée comme base pour les images Docker.", relatedCourseId: 'docker' },
  { id: 'distroless', term: 'Distroless', definition: "Images Docker de Google ne contenant que l'application et ses dépendances runtime, sans shell ni outils.", relatedCourseId: 'docker' },
  { id: 'health-check', term: 'Health Check (Docker)', definition: "Instruction vérifiant périodiquement si un container fonctionne correctement.", relatedCourseId: 'docker' },
  { id: 'docker-hub', term: 'Docker Hub', definition: "Registry publique par défaut de Docker, hébergeant des millions d'images communautaires.", relatedCourseId: 'docker' },
  { id: 'entrypoint', term: 'ENTRYPOINT', definition: "Instruction Dockerfile définissant la commande principale exécutée au démarrage du container.", relatedCourseId: 'docker' },
  { id: 'docker-cmd', term: 'CMD (Docker)', definition: "Instruction Dockerfile fournissant les arguments par défaut pour l'ENTRYPOINT.", relatedCourseId: 'docker' },
  { id: 'bind-mount', term: 'Bind Mount', definition: "Montage direct d'un répertoire de l'hôte dans un container Docker.", relatedCourseId: 'docker' },

  // === Kubernetes (30 terms) ===
  { id: 'pod', term: 'Pod', definition: 'Plus petite unité déployable dans Kubernetes, contenant un ou plusieurs containers.', relatedCourseId: 'kubernetes' },
  { id: 'deployment', term: 'Deployment', definition: 'Ressource Kubernetes qui gère un ensemble de Pods répliqués et leur mise à jour.', relatedCourseId: 'kubernetes' },
  { id: 'service-k8s', term: 'Service (K8s)', definition: 'Abstraction Kubernetes qui expose un ensemble de Pods comme service réseau.', relatedCourseId: 'kubernetes' },
  { id: 'ingress', term: 'Ingress', definition: "Ressource Kubernetes gérant l'accès externe aux services dans un cluster.", relatedCourseId: 'kubernetes' },
  { id: 'configmap', term: 'ConfigMap', definition: "Objet Kubernetes stockant des données de configuration non-confidentielles sous forme de paires clé-valeur.", relatedCourseId: 'kubernetes' },
  { id: 'secret-k8s', term: 'Secret (K8s)', definition: "Objet Kubernetes stockant des données sensibles (mots de passe, tokens) de manière encodée.", relatedCourseId: 'kubernetes' },
  { id: 'pv', term: 'PersistentVolume (PV)', definition: "Ressource de stockage provisionnée dans le cluster, indépendante du cycle de vie des Pods.", relatedCourseId: 'kubernetes' },
  { id: 'pvc', term: 'PersistentVolumeClaim (PVC)', definition: "Demande de stockage par un Pod, liée à un PersistentVolume disponible.", relatedCourseId: 'kubernetes' },
  { id: 'storageclass', term: 'StorageClass', definition: "Définition des types de stockage disponibles dans un cluster Kubernetes.", relatedCourseId: 'kubernetes' },
  { id: 'hpa', term: 'HPA (Horizontal Pod Autoscaler)', definition: "Contrôleur Kubernetes ajustant automatiquement le nombre de réplicas selon la charge.", relatedCourseId: 'kubernetes' },
  { id: 'vpa', term: 'VPA (Vertical Pod Autoscaler)', definition: "Contrôleur Kubernetes ajustant automatiquement les ressources (CPU/RAM) allouées aux Pods.", relatedCourseId: 'kubernetes' },
  { id: 'daemonset', term: 'DaemonSet', definition: "Ressource Kubernetes garantissant qu'un Pod s'exécute sur chaque nœud du cluster.", relatedCourseId: 'kubernetes' },
  { id: 'statefulset', term: 'StatefulSet', definition: "Contrôleur Kubernetes pour les applications nécessitant une identité réseau stable et du stockage persistant.", relatedCourseId: 'kubernetes' },
  { id: 'job-k8s', term: 'Job (K8s)', definition: "Ressource Kubernetes exécutant un ou plusieurs Pods jusqu'à complétion avec succès.", relatedCourseId: 'kubernetes' },
  { id: 'cronjob', term: 'CronJob', definition: "Ressource Kubernetes créant des Jobs selon un planning temporel (cron).", relatedCourseId: 'kubernetes' },
  { id: 'namespace', term: 'Namespace (K8s)', definition: "Mécanisme de partitionnement des ressources dans un cluster Kubernetes.", relatedCourseId: 'kubernetes' },
  { id: 'rbac', term: 'RBAC', definition: "Role-Based Access Control - système de contrôle d'accès basé sur les rôles dans Kubernetes.", relatedCourseId: 'kubernetes' },
  { id: 'helm', term: 'Helm', definition: "Gestionnaire de paquets pour Kubernetes permettant de définir et installer des applications.", relatedCourseId: 'kubernetes' },
  { id: 'helm-chart', term: 'Helm Chart', definition: "Package Helm contenant les templates et valeurs pour déployer une application sur Kubernetes.", relatedCourseId: 'kubernetes' },
  { id: 'kustomize', term: 'Kustomize', definition: "Outil de personnalisation de configurations Kubernetes sans templates, intégré à kubectl.", relatedCourseId: 'kubernetes' },
  { id: 'operator', term: 'Operator (K8s)', definition: "Pattern Kubernetes automatisant la gestion d'applications complexes via des contrôleurs personnalisés.", relatedCourseId: 'kubernetes' },
  { id: 'crd', term: 'CRD (Custom Resource Definition)', definition: "Extension de l'API Kubernetes permettant de définir ses propres types de ressources.", relatedCourseId: 'kubernetes' },
  { id: 'cni', term: 'CNI (Container Network Interface)', definition: "Standard définissant comment configurer le réseau pour les containers dans Kubernetes.", relatedCourseId: 'kubernetes' },
  { id: 'coredns', term: 'CoreDNS', definition: "Service DNS intégré à Kubernetes pour la résolution de noms des services du cluster.", relatedCourseId: 'kubernetes' },
  { id: 'etcd', term: 'etcd', definition: "Base de données clé-valeur distribuée servant de stockage pour l'état du cluster Kubernetes.", relatedCourseId: 'kubernetes' },
  { id: 'kubelet', term: 'kubelet', definition: "Agent s'exécutant sur chaque nœud, responsable de l'exécution des Pods assignés.", relatedCourseId: 'kubernetes' },
  { id: 'kubectl', term: 'kubectl', definition: "Outil en ligne de commande pour interagir avec l'API Kubernetes.", relatedCourseId: 'kubernetes' },
  { id: 'node-k8s', term: 'Node (K8s)', definition: "Machine (physique ou virtuelle) faisant partie d'un cluster Kubernetes.", relatedCourseId: 'kubernetes' },
  { id: 'control-plane', term: 'Control Plane', definition: "Ensemble des composants gérant l'état global du cluster Kubernetes (API server, scheduler, etc.).", relatedCourseId: 'kubernetes' },
  { id: 'replicaset', term: 'ReplicaSet', definition: "Contrôleur Kubernetes maintenant un nombre stable de réplicas de Pods en fonctionnement.", relatedCourseId: 'kubernetes' },

  // === Infrastructure (25 terms) ===
  { id: 'iac', term: 'IaC (Infrastructure as Code)', definition: "Gestion de l'infrastructure via des fichiers de configuration plutôt que manuellement.", relatedCourseId: 'terraform' },
  { id: 'terraform', term: 'Terraform', definition: "Outil IaC de HashiCorp permettant de provisionner l'infrastructure de manière déclarative.", relatedCourseId: 'terraform' },
  { id: 'terraform-state', term: 'Terraform State', definition: "Fichier qui enregistre l'état actuel de l'infrastructure gérée par Terraform.", relatedCourseId: 'terraform' },
  { id: 'provider-tf', term: 'Provider (Terraform)', definition: "Plugin Terraform qui interagit avec un service cloud ou API spécifique.", relatedCourseId: 'terraform' },
  { id: 'module-tf', term: 'Module (Terraform)', definition: "Ensemble réutilisable de ressources Terraform encapsulées dans un répertoire.", relatedCourseId: 'terraform' },
  { id: 'workspace-tf', term: 'Workspace (Terraform)', definition: "Environnement isolé permettant de gérer plusieurs états pour la même configuration.", relatedCourseId: 'terraform' },
  { id: 'hcl', term: 'HCL (HashiCorp Configuration Language)', definition: "Langage déclaratif de HashiCorp utilisé par Terraform pour décrire l'infrastructure.", relatedCourseId: 'terraform' },
  { id: 'cloudformation', term: 'CloudFormation', definition: "Service AWS d'IaC permettant de modéliser l'infrastructure via des templates JSON/YAML.", relatedCourseId: null },
  { id: 'pulumi', term: 'Pulumi', definition: "Outil IaC permettant de définir l'infrastructure avec des langages de programmation classiques.", relatedCourseId: null },
  { id: 'ansible', term: 'Ansible', definition: "Outil d'automatisation IT agentless pour la gestion de configuration et le déploiement.", relatedCourseId: 'ansible' },
  { id: 'playbook', term: 'Playbook (Ansible)', definition: "Fichier YAML décrivant l'état désiré d'un système et les tâches pour y parvenir.", relatedCourseId: 'ansible' },
  { id: 'inventory', term: 'Inventory (Ansible)', definition: "Fichier listant les hôtes et groupes d'hôtes gérés par Ansible.", relatedCourseId: 'ansible' },
  { id: 'role-ansible', term: 'Role (Ansible)', definition: "Unité réutilisable de contenu Ansible (tâches, handlers, variables, templates).", relatedCourseId: 'ansible' },
  { id: 'vault', term: 'Vault (HashiCorp)', definition: "Outil de gestion centralisée des secrets et du chiffrement des données sensibles.", relatedCourseId: null },
  { id: 'ansible-facts', term: 'Facts (Ansible)', definition: "Variables automatiquement collectées par Ansible sur les hôtes distants (OS, réseau, hardware).", relatedCourseId: 'ansible' },
  { id: 'idempotence', term: 'Idempotence', definition: "Propriété d'une opération qui produit le même résultat qu'elle soit exécutée une ou plusieurs fois.", relatedCourseId: 'ansible' },
  { id: 'immutable-infra', term: 'Infrastructure Immuable', definition: "Approche où les serveurs ne sont jamais modifiés après déploiement mais remplacés.", relatedCourseId: 'terraform' },
  { id: 'cattle-vs-pets', term: 'Cattle vs Pets', definition: "Métaphore DevOps : les serveurs jetables (cattle) vs les serveurs uniques et choyés (pets).", relatedCourseId: null },
  { id: 'drift', term: 'Drift (Infrastructure)', definition: "Écart entre l'état réel de l'infrastructure et l'état défini dans le code.", relatedCourseId: 'terraform' },
  { id: 'provisioner', term: 'Provisioner', definition: "Composant qui exécute des scripts sur une ressource après sa création (Terraform/Packer).", relatedCourseId: 'terraform' },
  { id: 'packer', term: 'Packer', definition: "Outil HashiCorp pour créer des images machine identiques pour plusieurs plateformes.", relatedCourseId: null },
  { id: 'ansible-galaxy', term: 'Ansible Galaxy', definition: "Plateforme communautaire de partage de rôles et collections Ansible réutilisables.", relatedCourseId: 'ansible' },
  { id: 'terraform-plan', term: 'Terraform Plan', definition: "Commande affichant un aperçu des modifications que Terraform va appliquer à l'infrastructure.", relatedCourseId: 'terraform' },
  { id: 'terraform-apply', term: 'Terraform Apply', definition: "Commande appliquant les changements planifiés à l'infrastructure réelle.", relatedCourseId: 'terraform' },
  { id: 'ansible-handler', term: 'Handler (Ansible)', definition: "Tâche Ansible déclenchée uniquement quand une autre tâche notifie un changement.", relatedCourseId: 'ansible' },

  // === Git (24 terms) ===
  { id: 'git-rebase', term: 'Rebase (Git)', definition: "Opération Git qui réapplique des commits sur une nouvelle base, créant un historique linéaire.", relatedCourseId: 'git-avance' },
  { id: 'git-cherry-pick', term: 'Cherry-pick (Git)', definition: "Appliquer un commit spécifique d'une branche sur une autre.", relatedCourseId: 'git-avance' },
  { id: 'git-bisect', term: 'Bisect (Git)', definition: "Commande Git utilisant une recherche binaire pour trouver le commit introduisant un bug.", relatedCourseId: 'git-avance' },
  { id: 'git-stash', term: 'Stash (Git)', definition: "Commande sauvegardant temporairement des modifications non commitées pour nettoyer le répertoire de travail.", relatedCourseId: 'git-avance' },
  { id: 'git-worktree', term: 'Worktree (Git)', definition: "Fonctionnalité permettant d'avoir plusieurs répertoires de travail liés au même dépôt Git.", relatedCourseId: 'git-avance' },
  { id: 'git-hook', term: 'Hook (Git)', definition: "Script exécuté automatiquement lors d'événements Git (pre-commit, post-push, etc.).", relatedCourseId: 'git-avance' },
  { id: 'git-submodule', term: 'Submodule (Git)', definition: "Mécanisme permettant d'inclure un dépôt Git comme sous-répertoire d'un autre.", relatedCourseId: 'git-avance' },
  { id: 'git-subtree', term: 'Subtree (Git)', definition: "Alternative aux submodules intégrant le code d'un dépôt externe directement dans l'historique.", relatedCourseId: 'git-avance' },
  { id: 'git-reflog', term: 'Reflog (Git)', definition: "Journal local enregistrant toutes les modifications des références Git, utile pour récupérer des commits perdus.", relatedCourseId: 'git-avance' },
  { id: 'git-squash', term: 'Squash (Git)', definition: "Combiner plusieurs commits en un seul pour un historique plus propre.", relatedCourseId: 'git-avance' },
  { id: 'git-fixup', term: 'Fixup (Git)', definition: "Commit destiné à corriger un commit précédent, automatiquement fusionné lors d'un rebase interactif.", relatedCourseId: 'git-avance' },
  { id: 'merge-commit', term: 'Merge Commit', definition: "Commit créé lors de la fusion de deux branches, préservant l'historique des deux.", relatedCourseId: 'git-avance' },
  { id: 'fast-forward', term: 'Fast-Forward (Git)', definition: "Type de merge où la branche cible avance simplement au dernier commit de la branche source.", relatedCourseId: 'git-avance' },
  { id: 'conflict', term: 'Conflict (Git)', definition: "Situation où Git ne peut pas fusionner automatiquement des modifications concurrentes.", relatedCourseId: 'git-avance' },
  { id: 'branch', term: 'Branch (Git)', definition: "Pointeur mobile vers un commit, permettant le développement parallèle.", relatedCourseId: 'git-avance' },
  { id: 'tag', term: 'Tag (Git)', definition: "Référence immuable pointant vers un commit spécifique, souvent utilisée pour marquer des releases.", relatedCourseId: 'git-avance' },
  { id: 'remote', term: 'Remote (Git)', definition: "Référence vers un dépôt Git distant (origin, upstream).", relatedCourseId: 'git-avance' },
  { id: 'fetch', term: 'Fetch (Git)', definition: "Télécharger les modifications d'un dépôt distant sans les fusionner localement.", relatedCourseId: 'git-avance' },
  { id: 'pull', term: 'Pull (Git)', definition: "Combinaison de fetch et merge, récupérant et intégrant les modifications distantes.", relatedCourseId: 'git-avance' },
  { id: 'push', term: 'Push (Git)', definition: "Envoyer les commits locaux vers un dépôt distant.", relatedCourseId: 'git-avance' },
  { id: 'clone', term: 'Clone (Git)', definition: "Créer une copie locale complète d'un dépôt Git distant.", relatedCourseId: 'git-avance' },
  { id: 'fork', term: 'Fork', definition: "Copie personnelle d'un dépôt sur une plateforme, permettant de contribuer via Pull/Merge Request.", relatedCourseId: 'git-avance' },
  { id: 'pull-request', term: 'Pull Request (PR)', definition: "Demande de fusion de code proposant des modifications d'une branche vers une autre.", relatedCourseId: 'git-avance' },
  { id: 'merge-request', term: 'Merge Request (MR)', definition: "Équivalent GitLab du Pull Request, demande de fusion de code entre branches.", relatedCourseId: 'gitlab-ci' },

  // === Monitoring & Observability (18 terms) ===
  { id: 'prometheus', term: 'Prometheus', definition: "Système de monitoring open-source avec base de données temporelle et langage de requête PromQL.", relatedCourseId: null },
  { id: 'grafana', term: 'Grafana', definition: "Plateforme de visualisation et dashboarding pour métriques, logs et traces.", relatedCourseId: null },
  { id: 'alerting', term: 'Alerting', definition: "Mécanisme de notification automatique quand des métriques dépassent des seuils définis.", relatedCourseId: null },
  { id: 'metrics', term: 'Métriques', definition: "Mesures numériques quantifiant les performances et le comportement d'un système (CPU, latence, erreurs).", relatedCourseId: null },
  { id: 'logs', term: 'Logs', definition: "Enregistrements textuels horodatés des événements survenant dans un système.", relatedCourseId: null },
  { id: 'traces', term: 'Traces (Distributed Tracing)', definition: "Suivi du parcours d'une requête à travers les différents services d'un système distribué.", relatedCourseId: null },
  { id: 'sli', term: 'SLI (Service Level Indicator)', definition: "Métrique quantitative mesurant un aspect spécifique du niveau de service (latence, disponibilité).", relatedCourseId: null },
  { id: 'slo', term: 'SLO (Service Level Objective)', definition: "Objectif cible pour un SLI, définissant le niveau de service acceptable.", relatedCourseId: null },
  { id: 'sla', term: 'SLA (Service Level Agreement)', definition: "Contrat formel entre fournisseur et client définissant les niveaux de service garantis.", relatedCourseId: null },
  { id: 'mttr', term: 'MTTR (Mean Time To Recover)', definition: "Temps moyen nécessaire pour restaurer un service après une panne.", relatedCourseId: null },
  { id: 'mttf', term: 'MTTF (Mean Time To Failure)', definition: "Temps moyen entre la mise en service et la première défaillance d'un système.", relatedCourseId: null },
  { id: 'observability', term: 'Observabilité', definition: "Capacité à comprendre l'état interne d'un système à partir de ses sorties (métriques, logs, traces).", relatedCourseId: null },
  { id: 'apm', term: 'APM (Application Performance Monitoring)', definition: "Surveillance des performances applicatives incluant temps de réponse, transactions et erreurs.", relatedCourseId: null },
  { id: 'elk', term: 'ELK Stack', definition: "Suite Elasticsearch, Logstash et Kibana pour la collecte, l'indexation et la visualisation de logs.", relatedCourseId: null },
  { id: 'fluentd', term: 'Fluentd', definition: "Collecteur de données open-source unifiant la collecte et la consommation de logs.", relatedCourseId: null },
  { id: 'monitoring', term: 'Monitoring', definition: "Surveillance continue des systèmes pour détecter et résoudre les problèmes.", relatedCourseId: null },
  { id: 'error-budget', term: 'Error Budget', definition: "Marge d'erreur tolérée calculée à partir du SLO (ex: 99.9% uptime = 43min de downtime/mois).", relatedCourseId: null },
  { id: 'golden-signals', term: 'Golden Signals', definition: "Les 4 métriques clés selon Google SRE : latence, trafic, erreurs et saturation.", relatedCourseId: null },

  // === Security (17 terms) ===
  { id: 'sast', term: 'SAST', definition: "Static Application Security Testing - analyse de sécurité du code source sans l'exécuter.", relatedCourseId: 'sonarqube' },
  { id: 'dast', term: 'DAST', definition: "Dynamic Application Security Testing - analyse de sécurité d'une application en cours d'exécution.", relatedCourseId: null },
  { id: 'iast', term: 'IAST', definition: "Interactive Application Security Testing - analyse combinant SAST et DAST pendant l'exécution des tests.", relatedCourseId: null },
  { id: 'sca', term: 'SCA (Software Composition Analysis)', definition: "Analyse des dépendances tierces pour détecter les vulnérabilités connues.", relatedCourseId: 'sonarqube' },
  { id: 'vulnerability', term: 'Vulnérabilité', definition: "Faiblesse dans un système pouvant être exploitée pour compromettre la sécurité.", relatedCourseId: null },
  { id: 'cve', term: 'CVE', definition: "Common Vulnerabilities and Exposures - identifiant unique pour une vulnérabilité de sécurité connue.", relatedCourseId: null },
  { id: 'secret-scanning', term: 'Secret Scanning', definition: "Détection automatique de secrets (API keys, mots de passe) accidentellement commités dans le code.", relatedCourseId: 'git-avance' },
  { id: 'code-signing', term: 'Code Signing', definition: "Signature cryptographique du code pour garantir son intégrité et son authenticité.", relatedCourseId: null },
  { id: 'rbac-security', term: 'RBAC (Role-Based Access Control)', definition: "Modèle de sécurité où les permissions sont attribuées selon les rôles des utilisateurs.", relatedCourseId: 'kubernetes' },
  { id: 'least-privilege', term: 'Least Privilege', definition: "Principe de sécurité accordant uniquement les permissions minimales nécessaires.", relatedCourseId: null },
  { id: 'zero-trust', term: 'Zero Trust', definition: "Modèle de sécurité ne faisant confiance à aucun acteur par défaut, vérifiant chaque requête.", relatedCourseId: null },
  { id: 'shift-left', term: 'Shift-Left Security', definition: "Approche intégrant les contrôles de sécurité le plus tôt possible dans le cycle de développement.", relatedCourseId: 'sonarqube' },
  { id: 'owasp', term: 'OWASP', definition: "Open Web Application Security Project - organisation fournissant des ressources sur la sécurité applicative.", relatedCourseId: null },
  { id: 'pentest', term: 'Penetration Testing', definition: "Test de sécurité simulant une attaque pour identifier les vulnérabilités exploitables.", relatedCourseId: null },
  { id: 'devsecops', term: 'DevSecOps', definition: "Intégration de la sécurité dans toutes les phases du cycle DevOps.", relatedCourseId: null },
  { id: 'supply-chain', term: 'Supply Chain Security', definition: "Sécurisation de la chaîne logicielle : dépendances, builds, distribution et déploiement.", relatedCourseId: null },
  { id: 'sbom', term: 'SBOM', definition: "Software Bill of Materials - inventaire des composants logiciels d'une application.", relatedCourseId: null },

  // === Cloud & Networking (22 terms) ===
  { id: 'load-balancer', term: 'Load Balancer', definition: "Composant réseau distribuant le trafic entre plusieurs serveurs.", relatedCourseId: null },
  { id: 'reverse-proxy', term: 'Reverse Proxy', definition: "Serveur intermédiaire recevant les requêtes clients et les transmettant aux serveurs backend.", relatedCourseId: null },
  { id: 'cdn', term: 'CDN (Content Delivery Network)', definition: "Réseau de serveurs distribués géographiquement pour servir le contenu au plus près des utilisateurs.", relatedCourseId: null },
  { id: 'dns', term: 'DNS', definition: "Système traduisant les noms de domaine en adresses IP.", relatedCourseId: null },
  { id: 'ssl-tls', term: 'SSL/TLS', definition: "Protocoles cryptographiques sécurisant les communications réseau.", relatedCourseId: null },
  { id: 'vpc', term: 'VPC (Virtual Private Cloud)', definition: "Réseau virtuel isolé dans le cloud, offrant un contrôle total sur l'environnement réseau.", relatedCourseId: null },
  { id: 'subnet', term: 'Subnet', definition: "Subdivision d'un réseau IP en segments logiques plus petits.", relatedCourseId: null },
  { id: 'firewall', term: 'Firewall', definition: "Système de sécurité réseau filtrant le trafic entrant et sortant selon des règles définies.", relatedCourseId: null },
  { id: 'nat', term: 'NAT (Network Address Translation)', definition: "Technique traduisant les adresses IP privées en adresses publiques pour accéder à Internet.", relatedCourseId: null },
  { id: 'gateway', term: 'Gateway', definition: "Point d'entrée/sortie d'un réseau, routant le trafic entre réseaux différents.", relatedCourseId: null },
  { id: 'public-cloud', term: 'Cloud Public', definition: "Infrastructure cloud partagée entre plusieurs clients, gérée par un fournisseur (AWS, Azure, GCP).", relatedCourseId: null },
  { id: 'private-cloud', term: 'Cloud Privé', definition: "Infrastructure cloud dédiée à une seule organisation, sur site ou hébergée.", relatedCourseId: null },
  { id: 'hybrid-cloud', term: 'Cloud Hybride', definition: "Combinaison de clouds publics et privés avec orchestration entre les environnements.", relatedCourseId: null },
  { id: 'multi-cloud', term: 'Multi-Cloud', definition: "Utilisation de services de plusieurs fournisseurs cloud simultanément.", relatedCourseId: null },
  { id: 'serverless', term: 'Serverless', definition: "Modèle d'exécution où le fournisseur cloud gère l'infrastructure, facturant à l'utilisation.", relatedCourseId: null },
  { id: 'faas', term: 'FaaS (Function as a Service)', definition: "Service cloud exécutant du code en réponse à des événements sans gestion de serveurs.", relatedCourseId: null },
  { id: 'iaas', term: 'IaaS (Infrastructure as a Service)', definition: "Service cloud fournissant des ressources d'infrastructure virtualisées (VMs, réseau, stockage).", relatedCourseId: null },
  { id: 'paas', term: 'PaaS (Platform as a Service)', definition: "Service cloud fournissant une plateforme pour développer et déployer des applications.", relatedCourseId: null },
  { id: 'saas', term: 'SaaS (Software as a Service)', definition: "Logiciel accessible via Internet sur abonnement, sans installation locale.", relatedCourseId: null },
  { id: 'service-mesh', term: 'Service Mesh', definition: "Couche d'infrastructure dédiée à la communication inter-services (Istio, Linkerd).", relatedCourseId: 'kubernetes' },
  { id: 'api-gateway', term: 'API Gateway', definition: "Point d'entrée unique gérant le routage, l'authentification et le rate limiting des APIs.", relatedCourseId: null },
  { id: 'cors', term: 'CORS', definition: "Cross-Origin Resource Sharing - mécanisme permettant les requêtes HTTP entre domaines différents.", relatedCourseId: null },

  // === Methodologies (16 terms) ===
  { id: 'agile', term: 'Agile', definition: "Méthodologie de développement itérative et incrémentale favorisant la collaboration et l'adaptation.", relatedCourseId: 'jira' },
  { id: 'scrum', term: 'Scrum', definition: "Framework Agile organisant le travail en sprints courts avec des rôles et cérémonies définis.", relatedCourseId: 'jira' },
  { id: 'kanban', term: 'Kanban', definition: "Méthode de gestion visuelle du flux de travail avec limitation du travail en cours (WIP).", relatedCourseId: 'jira' },
  { id: 'devops', term: 'DevOps', definition: "Culture et pratiques combinant développement logiciel et opérations IT pour raccourcir le cycle de développement.", relatedCourseId: null },
  { id: 'sre', term: 'SRE (Site Reliability Engineering)', definition: "Discipline appliquant les pratiques d'ingénierie logicielle aux opérations IT.", relatedCourseId: null },
  { id: 'platform-engineering', term: 'Platform Engineering', definition: "Discipline construisant des plateformes internes en self-service pour les équipes de développement.", relatedCourseId: null },
  { id: 'sprint', term: 'Sprint', definition: "Itération de durée fixe (1-4 semaines) dans Scrum, produisant un incrément potentiellement livrable.", relatedCourseId: 'jira' },
  { id: 'retrospective', term: 'Rétrospective', definition: "Cérémonie Scrum d'amélioration continue où l'équipe analyse son processus.", relatedCourseId: 'jira' },
  { id: 'standup', term: 'Daily Standup', definition: "Réunion quotidienne courte (15 min) où chaque membre partage progrès, plans et blocages.", relatedCourseId: 'jira' },
  { id: 'backlog', term: 'Backlog', definition: "Liste ordonnée de tout le travail à réaliser pour un produit.", relatedCourseId: 'jira' },
  { id: 'epic', term: 'Epic', definition: "Grande user story décomposable en stories plus petites, représentant une fonctionnalité majeure.", relatedCourseId: 'jira' },
  { id: 'user-story', term: 'User Story', definition: "Description courte d'une fonctionnalité du point de vue de l'utilisateur (En tant que... je veux... afin de...).", relatedCourseId: 'jira' },
  { id: 'velocity', term: 'Velocity', definition: "Mesure de la quantité de travail qu'une équipe peut accomplir par sprint.", relatedCourseId: 'jira' },
  { id: 'lean', term: 'Lean', definition: "Philosophie d'optimisation éliminant les gaspillages et maximisant la valeur livrée.", relatedCourseId: null },
  { id: 'dora-metrics', term: 'DORA Metrics', definition: "4 métriques clés DevOps : fréquence de déploiement, lead time, MTTR et taux d'échec.", relatedCourseId: null },
  { id: 'value-stream', term: 'Value Stream Mapping', definition: "Technique visualisant le flux de valeur de l'idée à la production pour identifier les goulots.", relatedCourseId: null },

  // === Quality (17 terms) ===
  { id: 'code-smell', term: 'Code Smell', definition: "Indication dans le code source d'un problème potentiel de design ou de qualité.", relatedCourseId: 'sonarqube' },
  { id: 'technical-debt', term: 'Dette technique', definition: "Coût implicite d'un travail supplémentaire causé par des choix de solutions rapides.", relatedCourseId: 'sonarqube' },
  { id: 'coverage', term: 'Code Coverage', definition: "Pourcentage du code source exécuté par les tests automatisés.", relatedCourseId: 'sonarqube' },
  { id: 'unit-test', term: 'Test Unitaire', definition: "Test vérifiant le comportement d'une unité isolée de code (fonction, méthode).", relatedCourseId: null },
  { id: 'integration-test', term: "Test d'Intégration", definition: "Test vérifiant l'interaction correcte entre plusieurs composants ou services.", relatedCourseId: null },
  { id: 'e2e-test', term: 'Test End-to-End (E2E)', definition: "Test simulant le parcours complet d'un utilisateur à travers l'application.", relatedCourseId: null },
  { id: 'tdd', term: 'TDD (Test-Driven Development)', definition: "Méthodologie écrivant les tests avant le code de production (Red-Green-Refactor).", relatedCourseId: null },
  { id: 'bdd', term: 'BDD (Behavior-Driven Development)', definition: "Extension du TDD décrivant le comportement attendu en langage naturel (Given-When-Then).", relatedCourseId: null },
  { id: 'mutation-testing', term: 'Mutation Testing', definition: "Technique évaluant la qualité des tests en introduisant des modifications dans le code.", relatedCourseId: null },
  { id: 'static-analysis', term: 'Analyse Statique', definition: "Examen automatisé du code source sans exécution pour détecter bugs et violations.", relatedCourseId: 'sonarqube' },
  { id: 'linting', term: 'Linting', definition: "Analyse statique vérifiant le respect des conventions de style et détectant les erreurs courantes.", relatedCourseId: null },
  { id: 'formatting', term: 'Formatting', definition: "Mise en forme automatique du code selon des règles de style prédéfinies (Prettier, Black).", relatedCourseId: null },
  { id: 'code-review', term: 'Code Review', definition: "Relecture du code par des pairs pour détecter bugs, améliorer la qualité et partager les connaissances.", relatedCourseId: 'git-avance' },
  { id: 'pair-programming', term: 'Pair Programming', definition: "Technique où deux développeurs travaillent ensemble sur le même code en temps réel.", relatedCourseId: null },
  { id: 'sonar-gate', term: 'Quality Gate', definition: "Ensemble de conditions de qualité qu'un projet doit satisfaire pour être considéré comme prêt.", relatedCourseId: 'sonarqube' },
  { id: 'regression-test', term: 'Test de Régression', definition: "Tests vérifiants que les modifications n'ont pas introduit de nouveaux bugs.", relatedCourseId: null },
  { id: 'smoke-test', term: 'Smoke Test', definition: "Tests rapides vérifiant les fonctionnalités critiques après un déploiement.", relatedCourseId: null },

  // === General DevOps (25 terms) ===
  { id: 'microservices', term: 'Microservices', definition: "Architecture où l'application est composée de petits services indépendants communiquant via APIs.", relatedCourseId: 'docker' },
  { id: 'monolith', term: 'Monolithe', definition: "Architecture où l'application est un seul bloc déployé comme une unité unique.", relatedCourseId: null },
  { id: 'api', term: 'API (Application Programming Interface)', definition: "Interface permettant à des logiciels de communiquer entre eux selon un contrat défini.", relatedCourseId: null },
  { id: 'rest', term: 'REST', definition: "Style architectural pour APIs utilisant les verbes HTTP et des ressources identifiées par URLs.", relatedCourseId: null },
  { id: 'grpc', term: 'gRPC', definition: "Framework RPC haute performance de Google utilisant Protocol Buffers et HTTP/2.", relatedCourseId: null },
  { id: 'message-queue', term: 'Message Queue', definition: "Système de communication asynchrone entre services via files d'attente (RabbitMQ, Kafka).", relatedCourseId: null },
  { id: 'event-driven', term: 'Event-Driven Architecture', definition: "Architecture où les composants communiquent par émission et réception d'événements.", relatedCourseId: null },
  { id: 'cqrs', term: 'CQRS', definition: "Command Query Responsibility Segregation - séparation des opérations de lecture et d'écriture.", relatedCourseId: null },
  { id: 'twelve-factor', term: '12-Factor App', definition: "Méthodologie pour construire des applications SaaS modernes, portables et scalables.", relatedCourseId: 'docker' },
  { id: 'chaos-engineering', term: 'Chaos Engineering', definition: "Pratique d'injection de pannes contrôlées pour tester la résilience d'un système.", relatedCourseId: null },
  { id: 'toil', term: 'Toil', definition: "Travail manuel, répétitif et automatisable lié aux opérations d'un service en production.", relatedCourseId: null },
  { id: 'runbook', term: 'Runbook', definition: "Document procédural décrivant les étapes pour résoudre un incident ou effectuer une opération.", relatedCourseId: null },
  { id: 'incident', term: 'Incident', definition: "Événement non planifié causant une interruption ou dégradation d'un service.", relatedCourseId: null },
  { id: 'post-mortem', term: 'Post-Mortem', definition: "Analyse rétrospective d'un incident pour en comprendre les causes et prévenir sa récurrence.", relatedCourseId: null },
  { id: 'gitops', term: 'GitOps', definition: "Paradigme opérationnel utilisant Git comme source unique de vérité pour l'infrastructure.", relatedCourseId: 'git-avance' },
  { id: 'yaml', term: 'YAML', definition: "Format de sérialisation de données lisible par l'humain, utilisé pour les fichiers de configuration.", relatedCourseId: null },
  { id: 'json', term: 'JSON', definition: "Format de données léger basé sur la notation objet JavaScript, omniprésent dans les APIs.", relatedCourseId: null },
  { id: 'scm', term: 'SCM (Source Control Management)', definition: "Système de gestion du code source permettant le suivi des modifications.", relatedCourseId: 'git-avance' },
  { id: 'repository-art', term: 'Repository (Artifactory)', definition: "Espace de stockage organisé pour les artifacts binaires.", relatedCourseId: 'artifactory' },
  { id: 'circuit-breaker', term: 'Circuit Breaker', definition: "Pattern de résilience coupant les appels vers un service défaillant pour éviter la cascade d'erreurs.", relatedCourseId: null },
  { id: 'rate-limiting', term: 'Rate Limiting', definition: "Limitation du nombre de requêtes acceptées par unité de temps pour protéger un service.", relatedCourseId: null },
  { id: 'blue-green-db', term: 'Database Migration', definition: "Gestion versionnée des modifications de schéma de base de données (Flyway, Liquibase).", relatedCourseId: null },
  { id: 'container-registry', term: 'Container Registry', definition: "Service centralisant le stockage, la gestion et la distribution d'images de containers.", relatedCourseId: 'artifactory' },
  { id: 'infrastructure-testing', term: 'Infrastructure Testing', definition: "Tests automatisés validant la conformité de l'infrastructure (InSpec, Terratest).", relatedCourseId: 'terraform' },
  { id: 'feature-branch', term: 'Feature Branch', definition: "Branche Git dédiée au développement d'une fonctionnalité spécifique avant fusion.", relatedCourseId: 'git-avance' },
];
