export const seedData = {
  courses: [
    {
      id: 'artifactory', title: 'JFrog Artifactory', subtitle: 'Gestionnaire de dépôts universels',
      description: 'Maîtrisez Artifactory, le gestionnaire de dépôts d\'artefacts universel. Apprenez à gérer vos binaires, conteneurs et packages dans un référentiel centralisé.',
      icon: '📦', color: '#41BF47', duration: '12 heures', level: 'Intermédiaire', category: 'Gestion des artefacts',
      prerequisites: JSON.stringify(['Connaissances de base en CI/CD', 'Familiarité avec Maven/Gradle/npm']),
      objectives: JSON.stringify(['Installer et configurer Artifactory', 'Gérer des dépôts locaux, distants et virtuels', 'Intégrer dans un pipeline CI/CD', 'Gérer les permissions', 'Utiliser promotion et rétention']),
    },
    {
      id: 'sonarqube', title: 'SonarQube', subtitle: 'Analyse de qualité de code',
      description: 'Apprenez à utiliser SonarQube pour analyser la qualité de votre code, détecter bugs, vulnérabilités et code smells.',
      icon: '🔍', color: '#4E9BCD', duration: '10 heures', level: 'Intermédiaire', category: 'Qualité du code',
      prerequisites: JSON.stringify(['Connaissances en programmation', 'Notions de CI/CD']),
      objectives: JSON.stringify(['Installer et configurer SonarQube', 'Analyser avec SonarScanner', 'Comprendre les métriques', 'Configurer Quality Gates', 'Intégrer dans Jenkins/GitLab CI']),
    },
    {
      id: 'doors', title: 'IBM DOORS', subtitle: 'Gestion des exigences',
      description: 'Maîtrisez IBM DOORS pour la gestion des exigences dans les projets complexes. Traçabilité, liens et analyse d\'impact.',
      icon: '📋', color: '#054ADA', duration: '15 heures', level: 'Avancé', category: 'Gestion des exigences',
      prerequisites: JSON.stringify(['Notions d\'ingénierie système', 'Gestion de projet']),
      objectives: JSON.stringify(['Naviguer dans DOORS', 'Créer des modules d\'exigences', 'Établir la traçabilité', 'Utiliser vues et filtres', 'Générer rapports', 'Administrer projets']),
    },
    {
      id: 'clearcase', title: 'IBM ClearCase', subtitle: 'Gestion de configuration logicielle',
      description: 'Apprenez IBM Rational ClearCase pour la gestion de configuration. Versionnement, branches, vues dynamiques et UCM.',
      icon: '🌿', color: '#1F70C1', duration: '14 heures', level: 'Avancé', category: 'Gestion de configuration',
      prerequisites: JSON.stringify(['Expérience avec un SCM (Git, SVN)', 'Connaissances système']),
      objectives: JSON.stringify(['Architecture VOB/View', 'Vues dynamiques et snapshot', 'Branching et merging', 'UCM', 'Administration VOBs', 'Migration vers Git']),
    },
    {
      id: 'klocwork', title: 'Klocwork', subtitle: 'Analyse statique de code',
      description: 'Découvrez Klocwork pour l\'analyse statique C, C++, Java, C#. Défauts critiques, vulnérabilités et conformité aux standards.',
      icon: '🛡️', color: '#E74C3C', duration: '11 heures', level: 'Intermédiaire', category: 'Analyse statique',
      prerequisites: JSON.stringify(['Programmation C/C++ ou Java', 'Notions de sécurité logicielle']),
      objectives: JSON.stringify(['Installer Klocwork', 'Lancer des analyses', 'Interpréter les résultats', 'Configurer checkers', 'Intégrer dans CI/CD', 'Standards MISRA et CERT']),
    },
    {
      id: 'jenkins', title: 'Jenkins', subtitle: 'Automatisation CI/CD',
      description: 'Maîtrisez Jenkins, le serveur d\'automatisation le plus populaire. Pipelines CI/CD, agents distribués, intégration outils.',
      icon: '🔧', color: '#D33833', duration: '16 heures', level: 'Débutant à Avancé', category: 'CI/CD',
      prerequisites: JSON.stringify(['Connaissances Linux de base', 'Familiarité avec Git']),
      objectives: JSON.stringify(['Installer Jenkins', 'Jobs Freestyle et Pipeline', 'Jenkinsfiles', 'Agents distribués', 'Plugins et sécurité', 'Docker et Kubernetes', 'Pipelines multibranches']),
    },
  ],

  modules: [
    { id: 'art-01', courseId: 'artifactory', title: 'Introduction à Artifactory', duration: '1h30', orderIndex: 1,
      theoryContent: '## Qu\'est-ce que JFrog Artifactory ?\n\nJFrog Artifactory est un gestionnaire de dépôts binaires universel supportant 27+ types de packages.\n\n### Pourquoi Artifactory ?\n- Dépôt universel : Maven, npm, Docker, PyPI, Go, Helm\n- Haute disponibilité et réplication\n- Scan de vulnérabilités avec Xray\n- API REST complète\n\n### Architecture à 3 niveaux\n1. **Dépôts locaux** : Stockage des artefacts internes\n2. **Dépôts distants** : Proxy/cache des dépôts externes\n3. **Dépôts virtuels** : Agrégation de dépôts',
      practiceContent: '### TP : Installation\n1. Lancez avec Docker : `docker run -d -p 8082:8082 releases-docker.jfrog.io/jfrog/artifactory-oss:latest`\n2. Accédez à http://localhost:8082\n3. Connectez-vous avec admin/password\n4. Créez un dépôt local Maven',
      keyPoints: JSON.stringify(['Gestionnaire universel de binaires', 'Supporte 27+ types de packages', 'Architecture dépôts locaux/distants/virtuels']) },
    { id: 'art-02', courseId: 'artifactory', title: 'Gestion des dépôts', duration: '2h', orderIndex: 2,
      theoryContent: '## Types de dépôts\n\n### Dépôts Locaux\nDépôts physiques où vous déployez vos artefacts.\n```yaml\nPUT /api/repositories/my-maven-local\n{ "key": "my-maven-local", "rclass": "local", "packageType": "maven" }\n```\n\n### Dépôts Distants\nProxy et cache pour les dépôts externes (Maven Central, npmjs).\n\n### Dépôts Virtuels\nAgrègent plusieurs dépôts sous une URL unique.\n\n### Bonnes pratiques\n- Séparer releases et snapshots\n- Conventions de nommage\n- Politiques de rétention',
      practiceContent: '### TP : Configuration\n1. Créez `libs-release-local`\n2. Créez un dépôt distant vers Maven Central\n3. Créez un virtuel `libs-release` les agrégeant\n4. Déployez un JAR\n5. Résolvez une dépendance',
      keyPoints: JSON.stringify(['3 types : local, distant, virtuel', 'API REST pour automatisation', 'Politiques de rétention']) },

    { id: 'art-03', courseId: 'artifactory', title: 'Intégration CI/CD', duration: '2h30', orderIndex: 3,
      theoryContent: '## Artifactory dans le CI/CD\n\n### Avec Maven\n```xml\n<distributionManagement>\n  <repository>\n    <id>central</id>\n    <url>http://artifactory:8082/artifactory/libs-release-local</url>\n  </repository>\n</distributionManagement>\n```\n\n### Avec Jenkins\nPlugin Artifactory : résolution, déploiement, Build Info, promotion.\n\n### Avec Docker\n```bash\ndocker login myregistry.jfrog.io\ndocker push myregistry.jfrog.io/my-app:1.0.0\n```\n\n### Build Info\nCapture les métadonnées complètes d\'un build.',
      practiceContent: '### TP : Pipeline\n1. Configurez le plugin Jenkins Artifactory\n2. Créez un Jenkinsfile qui résout, compile, déploie\n3. Publiez la Build Info\n4. Promouvez de staging à release',
      keyPoints: JSON.stringify(['Build Info pour traçabilité', 'Plugins natifs Jenkins/Maven/Gradle', 'Support Docker Registry']) },
    { id: 'sq-01', courseId: 'sonarqube', title: 'Introduction à SonarQube', duration: '1h30', orderIndex: 1,
      theoryContent: '## SonarQube - Qualité de code\n\nPlateforme open-source d\'inspection continue.\n\n### 3 piliers de la qualité\n1. **Fiabilité** : Bugs\n2. **Sécurité** : Vulnérabilités\n3. **Maintenabilité** : Code smells et dette technique\n\n### Métriques clés\n- Coverage, Duplications, Complexity, Technical Debt\n\n### Quality Gates\nCritères qu\'un projet doit satisfaire pour être validé.',
      practiceContent: '### TP : Premier scan\n1. `docker run -d -p 9000:9000 sonarqube:community`\n2. Créez un projet + token\n3. `mvn sonar:sonar -Dsonar.host.url=http://localhost:9000`\n4. Analysez le dashboard',
      keyPoints: JSON.stringify(['3 piliers : fiabilité, sécurité, maintenabilité', 'Quality Gates', 'Support multi-langages']) },

    { id: 'sq-02', courseId: 'sonarqube', title: 'Règles et profils qualité', duration: '2h', orderIndex: 2,
      theoryContent: '## Profils Qualité\n\nEnsemble de règles activées par langage.\n\n### Types de règles\n- Bug, Vulnerability, Code Smell, Security Hotspot\n\n### Sévérités\n1. Blocker\n2. Critical\n3. Major\n4. Minor\n5. Info\n\n### Personnalisation\nHéritez du profil par défaut, activez/désactivez des règles.',
      practiceContent: '### TP : Profils personnalisés\n1. Créez un profil Java personnalisé\n2. Héritez de "Sonar way"\n3. Activez des règles OWASP Top 10\n4. Assignez au projet\n5. Comparez les résultats',
      keyPoints: JSON.stringify(['Profils = ensemble de règles par langage', '4 types de règles', '5 niveaux de sévérité']) },
    { id: 'sq-03', courseId: 'sonarqube', title: 'Intégration pipeline', duration: '2h30', orderIndex: 3,
      theoryContent: '## SonarQube dans le CI/CD\n\n### Jenkins\n```groovy\npipeline {\n  stages {\n    stage(\'SonarQube\') {\n      steps {\n        withSonarQubeEnv(\'MySonarQube\') { sh \'mvn sonar:sonar\' }\n      }\n    }\n    stage(\'Quality Gate\') {\n      steps { waitForQualityGate abortPipeline: true }\n    }\n  }\n}\n```\n\n### Branch Analysis\nAnalyse des branches et Pull Requests.',
      practiceContent: '### TP : Pipeline complet\n1. Configurez SonarQube dans Jenkins\n2. Créez un Quality Gate strict\n3. Pipeline : compile → tests → SonarQube → Quality Gate\n4. Vérifiez le blocage si non conforme',
      keyPoints: JSON.stringify(['waitForQualityGate bloque si non conforme', 'Analyse branches/PRs', 'Webhooks asynchrones']) },
    { id: 'doors-01', courseId: 'doors', title: 'Introduction à IBM DOORS', duration: '2h', orderIndex: 1,
      theoryContent: '## IBM DOORS - Gestion des exigences\n\nOutil de référence pour les industries réglementées (aéro, auto, défense).\n\n### Concepts fondamentaux\n- **Module** : Document d\'exigences\n- **Objet** : Une exigence\n- **Attribut** : Propriété (statut, priorité)\n- **Lien** : Relation de traçabilité\n- **Vue** : Présentation filtrée\n\n### DOORS vs DOORS Next (DNG)\n- Classic : Client lourd\n- DNG : Web, plateforme Jazz',
      practiceContent: '### TP : Premiers pas\n1. Connectez-vous au serveur DOORS\n2. Explorez la structure\n3. Ouvrez un module formel\n4. Identifiez les attributs\n5. Naviguez les liens',
      keyPoints: JSON.stringify(['Outil de référence industries réglementées', 'Modules, Objets, Attributs, Liens', 'Traçabilité bidirectionnelle']) },

    { id: 'doors-02', courseId: 'doors', title: 'Création et gestion des exigences', duration: '3h', orderIndex: 2,
      theoryContent: '## Rédaction d\'exigences\n\n### Bonnes pratiques\nUne bonne exigence est : Atomique, Vérifiable, Non ambiguë, Traçable.\n\n### Attributs standards\n- ID, Status (Draft/Approved), Priority (Must/Should/Could), Rationale, Verification\n\n### DXL - DOORS eXtension Language\n```dxl\nModule m = current\nObject o\nfor o in m do {\n  if (o."Status" == "Draft") print o."Object Heading"\n}\n```',
      practiceContent: '### TP : Module d\'exigences\n1. Créez "Exigences Système"\n2. Définissez attributs personnalisés\n3. Rédigez 10 exigences\n4. Créez une vue filtrée\n5. Exportez en tabulaire',
      keyPoints: JSON.stringify(['Exigences atomiques, vérifiables, non ambiguës', 'Attributs personnalisables', 'DXL pour automatisation']) },
    { id: 'doors-03', courseId: 'doors', title: 'Traçabilité et analyse d\'impact', duration: '3h', orderIndex: 3,
      theoryContent: '## Traçabilité\n\n### Types de liens\n- In-links, Out-links, Liens internes\n\n### Matrice de traçabilité\nBesoins Client → Exigences Système → Exigences SW → Tests\n\n### Liens suspects\nQuand un objet source est modifié, les liens deviennent "suspects" jusqu\'à validation.\n\n### Métriques\n- Couverture : % d\'exigences liées\n- Liens suspects : À revalider\n- Orphelins : Sans lien amont/aval',
      practiceContent: '### TP : Traçabilité\n1. Créez un module "Cas de test"\n2. Établissez des liens exigences↔tests\n3. Modifiez une exigence → observez liens suspects\n4. Générez une matrice de traçabilité\n5. Identifiez les orphelins',
      keyPoints: JSON.stringify(['Liens suspects = changement non validé', 'Matrice de traçabilité complète', 'Couverture et orphelins']) },
    { id: 'cc-01', courseId: 'clearcase', title: 'Architecture et concepts ClearCase', duration: '2h', orderIndex: 1,
      theoryContent: '## IBM Rational ClearCase\n\nSCM d\'entreprise pour les grands projets.\n\n### VOB (Versioned Object Base)\nLe dépôt : fichiers versionnés, métadonnées, historique.\n\n### View (Vue)\n- **Dynamique** : Montée via MVFS, toujours à jour\n- **Snapshot** : Copie locale\n\n### Config Spec\n```\nelement * CHECKEDOUT\nelement * .../my_branch/LATEST\nelement * /main/LATEST\n```\n\n### Base ClearCase vs UCM\n- Base : Flexible, manuel\n- UCM : Processus structuré',
      practiceContent: '### TP : Premiers pas\n1. `cleartool lsvob`\n2. `cleartool mkview -tag myview`\n3. Configurez le config spec\n4. Naviguez le VOB\n5. `cleartool lshistory`',
      keyPoints: JSON.stringify(['VOB = dépôt, View = espace de travail', 'Vues dynamiques vs snapshot', 'Config Spec pour sélection de versions']) },

    { id: 'cc-02', courseId: 'clearcase', title: 'Opérations quotidiennes', duration: '3h', orderIndex: 2,
      theoryContent: '## Opérations ClearCase\n\n### Checkout / Checkin\n```bash\ncleartool checkout -c "Fix bug #123" myfile.c\ncleartool checkin -c "Bug fixed" myfile.c\ncleartool uncheckout myfile.c\n```\n\n### Branching\n```bash\ncleartool mkbrtype -c "Feature X" feature_x\ncleartool mkbranch feature_x myfile.c\n```\n\n### Merge\n```bash\ncleartool findmerge . -fversion .../feature_x/LATEST -merge\n```\n\n### Labels\n```bash\ncleartool mklbtype -c "Release 1.0" REL_1_0\ncleartool mklabel REL_1_0 myfile.c@@/main/3\n```',
      practiceContent: '### TP : Workflow complet\n1. Checkout un fichier\n2. Modifiez et checkin\n3. Créez une branche feature\n4. Travaillez sur la branche\n5. Mergez vers main\n6. Appliquez un label',
      keyPoints: JSON.stringify(['Checkout réservé par défaut', 'Branches typées', 'Labels pour marquer les versions']) },
    { id: 'cc-03', courseId: 'clearcase', title: 'UCM et administration', duration: '3h', orderIndex: 3,
      theoryContent: '## UCM - Unified Change Management\n\n### Concepts\n- Projet, Stream, Activité, Baseline, Composant\n\n### Workflow UCM\n1. Développeur crée une activité\n2. Travaille dans son stream\n3. Deliver vers intégration\n4. Intégrateur crée baseline\n5. Développeurs rebasent\n\n### Administration\n```bash\ncleartool mkvob -tag /vobs/myproject\ncleartool mkproject -c "Projet X" myproject\ncleartool mkstream -c "Dev" dev_stream\n```\n\n### Migration vers Git\ngit-cc, export historique, migration progressive.',
      practiceContent: '### TP : Projet UCM\n1. Créez un PVOB\n2. Créez un projet UCM\n3. Configurez streams\n4. Simulez : activité → deliver → baseline → rebase\n5. Discutez migration Git',
      keyPoints: JSON.stringify(['UCM structure le développement', 'Streams pour isolation', 'Baselines comme points stables']) },
    { id: 'kw-01', courseId: 'klocwork', title: 'Introduction à Klocwork', duration: '1h30', orderIndex: 1,
      theoryContent: '## Klocwork - Analyse statique\n\nOutil d\'analyse pour C, C++, C#, Java.\n\n### Pourquoi l\'analyse statique ?\n- Détection précoce (shift-left)\n- Vulnérabilités avant déploiement\n- Conformité MISRA, CERT, CWE, OWASP\n\n### Architecture\nDéveloppeur → kwcheck (local) → Serveur → kwbuildproject (complet) → Dashboard\n\n### Types de défauts\n- Buffer overflow, Null pointer, Resource leak, Race condition, SQL Injection, XSS',
      practiceContent: '### TP : Premier scan\n1. Installez kwcheck\n2. `kwinject make all`\n3. `kwcheck create --url http://kw-server:8080/project`\n4. `kwcheck run`\n5. Triez les issues',
      keyPoints: JSON.stringify(['Analyse statique C/C++/Java/C#', 'Conformité MISRA, CERT, CWE', 'Détection précoce shift-left']) },

    { id: 'kw-02', courseId: 'klocwork', title: 'Configuration et checkers', duration: '2h30', orderIndex: 2,
      theoryContent: '## Configuration des analyses\n\n### Taxonomies\n- C/C++ Critical, MISRA C/C++, CERT C/C++, CWE, OWASP\n\n### Configuration\n```\n+checker=MISRA.REQUIRED\n+checker=CERT.STR\n-checker=STYLE.*\nseverity:MISRA.*=critical\n```\n\n### Analyse incrémentale vs complète\n- kwcheck : locale, rapide\n- kwbuildproject : serveur, complète\n\n### Knowledge Base\nFlux de données, contrats de fonctions, état des variables.',
      practiceContent: '### TP : Configuration\n1. Activez checkers MISRA C:2012\n2. Créez un profil personnalisé\n3. Configurez les sévérités\n4. Ajoutez annotations (@non_null)\n5. Comparez incrémentale vs complète\n6. Rapport conformité MISRA',
      keyPoints: JSON.stringify(['Taxonomies : MISRA, CERT, CWE, OWASP', 'kwcheck local vs kwbuildproject serveur', 'Knowledge Base inter-procédurale']) },
    { id: 'kw-03', courseId: 'klocwork', title: 'Intégration CI/CD et reporting', duration: '2h', orderIndex: 3,
      theoryContent: '## Klocwork dans le CI/CD\n\n### Jenkins\n```groovy\npipeline {\n  stages {\n    stage(\'Inject\') { steps { sh \'kwinject make all\' } }\n    stage(\'Analyze\') { steps { sh \'kwbuildproject --url http://kw:8080/proj kwinject.out\' } }\n    stage(\'Check\') { steps { sh \'kwcheck list --status Analyze,Fix\' } }\n  }\n}\n```\n\n### Métriques\nIssues par sévérité, densité défauts (issues/KLOC), taux de résolution.\n\n### Cycle de vie\nNew → Analyze → Fix → Verify → Closed',
      practiceContent: '### TP : Pipeline\n1. Configurez Klocwork dans Jenkins\n2. Définissez des seuils de qualité\n3. Bloquez si nouvelles vulnérabilités\n4. Rapport de tendance\n5. Notifications\n6. Comparez avec SonarQube',
      keyPoints: JSON.stringify(['kwinject capture, kwbuildproject analyse', 'Seuils de qualité dans le pipeline', 'Métriques : densité défauts, taux résolution']) },
    { id: 'jen-01', courseId: 'jenkins', title: 'Introduction à Jenkins', duration: '2h', orderIndex: 1,
      theoryContent: '## Jenkins - Serveur d\'automatisation\n\nLe plus populaire avec 1800+ plugins.\n\n### Concepts\n- Job/Project, Build, Pipeline, Agent/Node, Plugin\n\n### Types de projets\n1. Freestyle\n2. Pipeline (Jenkinsfile)\n3. Multibranch Pipeline\n4. Organization Folder\n\n### Installation\n```bash\ndocker run -d -p 8080:8080 -p 50000:50000 \\\n  -v jenkins_home:/var/jenkins_home \\\n  jenkins/jenkins:lts\n```',
      practiceContent: '### TP : Installation\n1. Lancez Jenkins avec Docker\n2. Assistant d\'installation\n3. Plugins recommandés\n4. Premier job Freestyle\n5. Script shell\n6. Examinez la sortie',
      keyPoints: JSON.stringify(['Serveur CI/CD le plus populaire', '1800+ plugins', 'Freestyle vs Pipeline vs Multibranch']) },

    { id: 'jen-02', courseId: 'jenkins', title: 'Pipelines déclaratifs', duration: '3h', orderIndex: 2,
      theoryContent: '## Jenkins Pipeline - Déclaratif\n\n```groovy\npipeline {\n  agent any\n  environment { APP_VERSION = \'1.0.0\' }\n  stages {\n    stage(\'Build\') { steps { sh \'mvn clean package\' } }\n    stage(\'Test\') {\n      parallel {\n        stage(\'Unit\') { steps { sh \'mvn test\' } }\n        stage(\'Integration\') { steps { sh \'mvn verify\' } }\n      }\n    }\n    stage(\'Deploy\') {\n      when { branch \'main\' }\n      steps { sh \'kubectl apply -f k8s/\' }\n    }\n  }\n  post {\n    success { slackSend message: "OK" }\n    failure { slackSend message: "FAILED" }\n  }\n}\n```\n\n### Directives clés\nagent, environment, stages, when, post, parallel',
      practiceContent: '### TP : Pipeline complet\n1. Créez un Jenkinsfile\n2. Stages : Build, Test, Quality, Deploy\n3. Exécution parallèle\n4. Conditions (when)\n5. Notifications post-build\n6. Testez un échec',
      keyPoints: JSON.stringify(['Jenkinsfile = Pipeline as Code', 'Syntax déclarative structurée', 'parallel, when, post pour contrôle de flux']) },
    { id: 'jen-03', courseId: 'jenkins', title: 'Agents distribués et Docker', duration: '3h', orderIndex: 3,
      theoryContent: '## Architecture distribuée\n\n### Types d\'agents\n1. Permanent, 2. Cloud (Docker, K8s, EC2), 3. SSH\n\n### Agent Docker\n```groovy\npipeline {\n  agent { docker { image \'maven:3.9\' } }\n  stages { stage(\'Build\') { steps { sh \'mvn package\' } } }\n}\n```\n\n### Agent Kubernetes\n```groovy\nagent {\n  kubernetes {\n    yaml """\n    spec:\n      containers:\n      - name: maven\n        image: maven:3.9\n      - name: docker\n        image: docker:dind\n    """\n  }\n}\n```',
      practiceContent: '### TP : Agents\n1. Agent SSH permanent\n2. Pipeline agent Docker\n3. Plugin Kubernetes\n4. Pod template multi-conteneurs\n5. Build avec agent K8s\n6. Comparez performances',
      keyPoints: JSON.stringify(['Agents = exécuteurs distribués', 'Docker agents pour isolation', 'Kubernetes pour scaling dynamique']) },
    { id: 'jen-04', courseId: 'jenkins', title: 'Shared Libraries et bonnes pratiques', duration: '2h30', orderIndex: 4,
      theoryContent: '## Shared Libraries\n\nRéutilisation de code pipeline entre projets.\n\n### Structure\n```\nshared-library/\n├── vars/\n│   ├── buildJavaApp.groovy\n│   └── deployToK8s.groovy\n├── src/com/company/PipelineHelper.groovy\n└── resources/templates/\n```\n\n### Utilisation\n```groovy\n@Library(\'my-shared-lib\') _\npipeline {\n  stages {\n    stage(\'Build\') { steps { buildJavaApp(version: \'1.0.0\') } }\n    stage(\'Deploy\') { steps { deployToK8s(namespace: \'prod\') } }\n  }\n}\n```\n\n### Bonnes pratiques\n- Versionner les pipelines\n- Shared Libraries pour réutilisation\n- Credential Store pour secrets',
      practiceContent: '### TP : Shared Library\n1. Créez un repo pour la library\n2. Implémentez buildJavaApp dans vars/\n3. Implémentez notifySlack\n4. Configurez dans Jenkins\n5. Utilisez dans un pipeline\n6. Versionnez et testez',
      keyPoints: JSON.stringify(['Shared Libraries pour réutilisation', 'vars/ pour fonctions globales', 'Credentials Store pour secrets']) },
  ],

  quizQuestions: [
    { id: 'q-art-1', courseId: 'artifactory', moduleId: 'art-01', question: 'Quel type de dépôt sert de proxy/cache ?', options: JSON.stringify(['Dépôt local', 'Dépôt distant', 'Dépôt virtuel', 'Dépôt fédéré']), correctIndex: 1, explanation: 'Un dépôt distant sert de proxy et cache.' },
    { id: 'q-art-2', courseId: 'artifactory', moduleId: 'art-01', question: 'Combien de types de packages ?', options: JSON.stringify(['5+', '10+', '20+', '27+']), correctIndex: 3, explanation: 'Artifactory supporte 27+ types de packages.' },
    { id: 'q-art-3', courseId: 'artifactory', moduleId: 'art-02', question: 'Fonction d\'un dépôt virtuel ?', options: JSON.stringify(['Stocker', 'Cache', 'Agréger sous une URL', 'Répliquer']), correctIndex: 2, explanation: 'Un dépôt virtuel agrège plusieurs dépôts.' },
    { id: 'q-art-4', courseId: 'artifactory', moduleId: 'art-03', question: 'Qu\'est-ce que la Build Info ?', options: JSON.stringify(['Log', 'Métadonnées complètes d\'un build', 'Config serveur', 'Fichier version']), correctIndex: 1, explanation: 'Build Info = métadonnées complètes.' },
    { id: 'q-sq-1', courseId: 'sonarqube', moduleId: 'sq-01', question: 'Les 3 piliers SonarQube ?', options: JSON.stringify(['Perf, Sécu, Access.', 'Fiabilité, Sécurité, Maintenabilité', 'Coverage, Complexité, Duplication', 'Bugs, Vulns, Tests']), correctIndex: 1, explanation: 'Fiabilité, Sécurité et Maintenabilité.' },
    { id: 'q-sq-2', courseId: 'sonarqube', moduleId: 'sq-01', question: 'Qu\'est-ce qu\'un Quality Gate ?', options: JSON.stringify(['Firewall code', 'Critères de validation', 'Plugin sécurité', 'Profil qualité']), correctIndex: 1, explanation: 'Conditions pour valider un projet.' },
    { id: 'q-sq-3', courseId: 'sonarqube', moduleId: 'sq-02', question: 'Sévérité la plus haute ?', options: JSON.stringify(['Critical', 'Major', 'Blocker', 'Fatal']), correctIndex: 2, explanation: 'Blocker est la plus haute.' },

    { id: 'q-doors-1', courseId: 'doors', moduleId: 'doors-01', question: 'Que signifie DOORS ?', options: JSON.stringify(['Dynamic Object-Oriented Requirements System', 'Data-Oriented Object Repository', 'Document Object Organization', 'Dynamic Online Object Requirements']), correctIndex: 0, explanation: 'Dynamic Object-Oriented Requirements System.' },
    { id: 'q-doors-2', courseId: 'doors', moduleId: 'doors-02', question: 'Langage de script DOORS ?', options: JSON.stringify(['Python', 'JavaScript', 'DXL', 'Perl']), correctIndex: 2, explanation: 'DXL = DOORS eXtension Language.' },
    { id: 'q-doors-3', courseId: 'doors', moduleId: 'doors-03', question: 'Qu\'est-ce qu\'un lien suspect ?', options: JSON.stringify(['Lien vers module supprimé', 'Lien dont source modifiée sans revalidation', 'Lien par erreur', 'Lien vers Draft']), correctIndex: 1, explanation: 'Modifié sans revalidation.' },
    { id: 'q-cc-1', courseId: 'clearcase', moduleId: 'cc-01', question: 'Qu\'est-ce qu\'un VOB ?', options: JSON.stringify(['Virtual Object Browser', 'Versioned Object Base', 'Version-Oriented Build', 'View Object Backup']), correctIndex: 1, explanation: 'Versioned Object Base.' },
    { id: 'q-cc-2', courseId: 'clearcase', moduleId: 'cc-01', question: 'Vue dynamique vs snapshot ?', options: JSON.stringify(['Dynamique lecture seule', 'Dynamique via MVFS toujours à jour', 'Snapshot plus rapide', 'Pas de différence']), correctIndex: 1, explanation: 'MVFS = toujours à jour.' },
    { id: 'q-cc-3', courseId: 'clearcase', moduleId: 'cc-03', question: 'Qu\'est-ce qu\'une baseline UCM ?', options: JSON.stringify(['Branche', 'Snapshot stable composant', 'Type de merge', 'Fichier config']), correctIndex: 1, explanation: 'Instantané stable d\'un composant.' },
    { id: 'q-kw-1', courseId: 'klocwork', moduleId: 'kw-01', question: 'Langages Klocwork ?', options: JSON.stringify(['Python, Ruby, Go', 'C, C++, Java, C#', 'JS, TS, Rust', 'PHP, Perl, Shell']), correctIndex: 1, explanation: 'C, C++, Java et C#.' },
    { id: 'q-kw-2', courseId: 'klocwork', moduleId: 'kw-02', question: 'Standard automobile ?', options: JSON.stringify(['CERT', 'OWASP', 'MISRA', 'CWE']), correctIndex: 2, explanation: 'MISRA pour l\'automobile.' },
    { id: 'q-kw-3', courseId: 'klocwork', moduleId: 'kw-02', question: 'Commande capture build ?', options: JSON.stringify(['kwcheck', 'kwinject', 'kwbuildproject', 'kwadmin']), correctIndex: 1, explanation: 'kwinject intercepte le build.' },
    { id: 'q-jen-1', courseId: 'jenkins', moduleId: 'jen-01', question: 'Langage des Jenkinsfiles ?', options: JSON.stringify(['YAML', 'Python', 'Groovy', 'Bash']), correctIndex: 2, explanation: 'Groovy.' },
    { id: 'q-jen-2', courseId: 'jenkins', moduleId: 'jen-02', question: 'Directive conditionnelle ?', options: JSON.stringify(['if', 'condition', 'when', 'filter']), correctIndex: 2, explanation: 'when conditionne un stage.' },
    { id: 'q-jen-3', courseId: 'jenkins', moduleId: 'jen-03', question: 'Avantage agent K8s ?', options: JSON.stringify(['Plus rapide', 'Scaling dynamique + isolation', 'Plus facile', 'Tous plugins']), correctIndex: 1, explanation: 'Scaling dynamique et isolation.' },
    { id: 'q-jen-4', courseId: 'jenkins', moduleId: 'jen-04', question: 'Fonctions globales Shared Library ?', options: JSON.stringify(['src/', 'vars/', 'lib/', 'global/']), correctIndex: 1, explanation: 'vars/ pour les scripts globaux.' },
  ],
};
