// V3 New courses and modules
export const v3Courses = [
  {
    id: 'docker', title: 'Docker', subtitle: 'Conteneurisation d\'applications',
    description: 'Maîtrisez Docker pour conteneuriser vos applications. Images, containers, Dockerfile, docker-compose et bonnes pratiques.',
    icon: '🐳', color: '#2496ED', duration: '12 heures', level: 'Débutant à Intermédiaire', category: 'Conteneurisation',
    prerequisites: JSON.stringify(['Connaissances Linux de base', 'Familiarité avec la ligne de commande', 'Notions de réseau']),
    objectives: JSON.stringify(['Comprendre les containers', 'Écrire des Dockerfiles optimisés', 'Utiliser docker-compose', 'Gérer les volumes et réseaux', 'Publier des images', 'Bonnes pratiques de sécurité']),
  },
  {
    id: 'kubernetes', title: 'Kubernetes', subtitle: 'Orchestration de containers',
    description: 'Apprenez Kubernetes pour orchestrer vos containers en production. Pods, Deployments, Services, scaling et monitoring.',
    icon: '☸️', color: '#326CE5', duration: '16 heures', level: 'Intermédiaire à Avancé', category: 'Orchestration',
    prerequisites: JSON.stringify(['Maîtrise de Docker', 'Connaissances réseau (TCP/IP, DNS)', 'Familiarité avec YAML']),
    objectives: JSON.stringify(['Comprendre l\'architecture K8s', 'Déployer des applications', 'Configurer Services et Ingress', 'Gérer le scaling', 'Utiliser ConfigMaps et Secrets', 'Monitoring et troubleshooting']),
  },

  {
    id: 'terraform', title: 'Terraform', subtitle: 'Infrastructure as Code',
    description: 'Maîtrisez Terraform pour gérer votre infrastructure en tant que code. HCL, providers, state, modules et bonnes pratiques.',
    icon: '🏗️', color: '#7B42BC', duration: '14 heures', level: 'Intermédiaire', category: 'Infrastructure as Code',
    prerequisites: JSON.stringify(['Connaissances cloud (AWS/GCP/Azure)', 'Familiarité avec la CLI', 'Notions de réseau et infrastructure']),
    objectives: JSON.stringify(['Écrire du HCL', 'Configurer les providers', 'Gérer le state', 'Créer des modules réutilisables', 'Workspaces et environnements', 'Bonnes pratiques et CI/CD']),
  },
  {
    id: 'ansible', title: 'Ansible', subtitle: 'Automatisation de configuration',
    description: 'Découvrez Ansible pour automatiser la configuration de vos serveurs. Playbooks, inventories, roles et bonnes pratiques.',
    icon: '⚙️', color: '#EE0000', duration: '12 heures', level: 'Débutant à Intermédiaire', category: 'Automatisation',
    prerequisites: JSON.stringify(['Connaissances Linux', 'SSH configuré', 'Familiarité avec YAML']),
    objectives: JSON.stringify(['Installer et configurer Ansible', 'Écrire des playbooks', 'Gérer les inventories', 'Créer des roles', 'Utiliser Ansible Galaxy', 'Intégrer dans CI/CD']),
  },
  {
    id: 'gitlab-ci', title: 'GitLab CI', subtitle: 'CI/CD intégré à GitLab',
    description: 'Maîtrisez GitLab CI/CD pour automatiser vos pipelines. Configuration YAML, runners, environnements et déploiement.',
    icon: '🦊', color: '#FC6D26', duration: '10 heures', level: 'Intermédiaire', category: 'CI/CD',
    prerequisites: JSON.stringify(['Maîtrise de Git', 'Connaissances Docker', 'Notions de CI/CD']),
    objectives: JSON.stringify(['Écrire .gitlab-ci.yml', 'Configurer les runners', 'Stages et jobs', 'Variables et secrets', 'Environnements de déploiement', 'Optimisation des pipelines']),
  },
  {
    id: 'git-avance', title: 'Git Avancé', subtitle: 'Maîtrise avancée de Git',
    description: 'Allez au-delà des bases de Git. Rebase interactif, cherry-pick, bisect, hooks, sous-modules et stratégies de branching.',
    icon: '🔀', color: '#F05032', duration: '10 heures', level: 'Avancé', category: 'Gestion de code source',
    prerequisites: JSON.stringify(['Maîtrise des bases Git', 'Expérience avec branches et merge', 'Ligne de commande']),
    objectives: JSON.stringify(['Maîtriser rebase interactif', 'Utiliser cherry-pick et bisect', 'Configurer des hooks', 'Gérer les sous-modules', 'Stratégies de branching', 'Résolution de conflits avancée']),
  },
];


export const v3Modules = [
  // DOCKER
  { id: 'docker-mod1', courseId: 'docker', title: 'Containers et Images Docker', duration: '6h', orderIndex: 1,
    videoUrl: 'https://www.youtube.com/watch?v=3c-iBn73dDE',
    theoryContent: `## Les Fondamentaux de Docker\n\n### Qu'est-ce qu'un Container?\n\nUn container est une unité standard de logiciel qui empaquète le code et toutes ses dépendances. Contrairement aux machines virtuelles qui virtualisent le hardware, les containers virtualisent l'OS.\n\n### Architecture Docker\n\n- **Docker Engine** : le runtime qui gère les containers\n- **Docker Image** : template en lecture seule (layers)\n- **Docker Container** : instance exécutable d'une image\n- **Docker Registry** : stockage et distribution d'images\n\n### Commandes essentielles\n\n\`\`\`bash\n# Lancer un container\ndocker run -d --name mon-app -p 8080:80 nginx\n\n# Lister les containers\ndocker ps -a\n\n# Voir les logs\ndocker logs mon-app\n\n# Arrêter et supprimer\ndocker stop mon-app && docker rm mon-app\n\n# Lister les images\ndocker images\n\n# Supprimer une image\ndocker rmi nginx\n\`\`\`\n\n### Volumes et Persistance\n\nLes containers sont éphémères. Pour persister les données :\n\n\`\`\`bash\n# Volume nommé\ndocker run -v mon-volume:/data nginx\n\n# Bind mount\ndocker run -v $(pwd)/html:/usr/share/nginx/html nginx\n\`\`\`\n\n### Réseaux Docker\n\nDocker crée un réseau bridge par défaut. Pour la communication inter-containers :\n\n\`\`\`bash\ndocker network create mon-reseau\ndocker run --network mon-reseau --name api mon-api\ndocker run --network mon-reseau --name db postgres\n\`\`\``,
    practiceContent: `## TP : Premiers pas avec Docker\n\n### Exercice 1 : Lancer votre premier container\n\n\`\`\`bash\n# Lancez un container nginx\ndocker run -d --name web -p 8080:80 nginx\n\n# Vérifiez qu'il tourne\ncurl http://localhost:8080\n\n# Inspectez le container\ndocker inspect web\n\`\`\`\n\n### Exercice 2 : Volumes\n\n\`\`\`bash\n# Créez un fichier HTML\necho '<h1>Hello Docker!</h1>' > index.html\n\n# Montez-le dans nginx\ndocker run -d -p 8081:80 -v $(pwd)/index.html:/usr/share/nginx/html/index.html nginx\n\`\`\`\n\n### Exercice 3 : Multi-containers\n\n\`\`\`bash\ndocker network create tp-net\ndocker run -d --network tp-net --name redis redis:alpine\ndocker run -d --network tp-net -e REDIS_HOST=redis mon-app\n\`\`\``,
    keyPoints: JSON.stringify(['Container = process isolé partageant le kernel host', 'Image = layers empilés en lecture seule', 'Volume pour la persistance des données', 'Network pour la communication inter-containers', '-d pour mode détaché, -p pour port mapping']),
  },
  { id: 'docker-mod2', courseId: 'docker', title: 'Dockerfile et Docker Compose', duration: '6h', orderIndex: 2,
    videoUrl: 'https://www.youtube.com/watch?v=HG6yIjZapSA',
    theoryContent: `## Dockerfile et Docker Compose\n\n### Écrire un Dockerfile\n\nUn Dockerfile décrit comment construire une image :\n\n\`\`\`dockerfile\n# Image de base\nFROM node:18-alpine\n\n# Répertoire de travail\nWORKDIR /app\n\n# Copier les dépendances\nCOPY package*.json ./\nRUN npm ci --production\n\n# Copier le code\nCOPY . .\n\n# Port exposé\nEXPOSE 3000\n\n# Commande de démarrage\nCMD ["node", "server.js"]\n\`\`\`\n\n### Multi-stage builds\n\nOptimiser la taille de l'image :\n\n\`\`\`dockerfile\nFROM node:18 AS builder\nWORKDIR /app\nCOPY . .\nRUN npm ci && npm run build\n\nFROM node:18-alpine\nWORKDIR /app\nCOPY --from=builder /app/dist ./dist\nCOPY package*.json ./\nRUN npm ci --production\nCMD ["node", "dist/server.js"]\n\`\`\`\n\n### Docker Compose\n\nOrchestrer plusieurs services localement :\n\n\`\`\`yaml\nversion: '3.8'\nservices:\n  app:\n    build: .\n    ports:\n      - "3000:3000"\n    environment:\n      - DB_HOST=db\n    depends_on:\n      - db\n  db:\n    image: postgres:15\n    environment:\n      POSTGRES_PASSWORD: secret\n    volumes:\n      - pgdata:/var/lib/postgresql/data\n\nvolumes:\n  pgdata:\n\`\`\`\n\n### Bonnes pratiques Dockerfile\n\n- Utiliser des images **alpine** (plus légères)\n- Exploiter le **cache des layers** (COPY package.json avant le code)\n- Un seul process par container\n- Utiliser **.dockerignore**\n- Ne pas exécuter en **root** (USER node)`,
    practiceContent: `## TP : Créer et orchestrer\n\n### Exercice 1 : Écrire un Dockerfile\n\nCréez une app Node.js conteneurisée :\n\n\`\`\`dockerfile\nFROM node:18-alpine\nWORKDIR /app\nCOPY package*.json ./\nRUN npm install\nCOPY . .\nEXPOSE 3000\nCMD ["node", "index.js"]\n\`\`\`\n\n\`\`\`bash\ndocker build -t mon-app .\ndocker run -p 3000:3000 mon-app\n\`\`\`\n\n### Exercice 2 : Docker Compose\n\nCréez un docker-compose.yml avec app + Redis :\n\n\`\`\`yaml\nversion: '3.8'\nservices:\n  app:\n    build: .\n    ports:\n      - "3000:3000"\n    depends_on:\n      - redis\n  redis:\n    image: redis:alpine\n\`\`\`\n\n\`\`\`bash\ndocker compose up -d\ndocker compose logs -f\ndocker compose down\n\`\`\``,
    keyPoints: JSON.stringify(['FROM définit l\'image de base', 'Multi-stage build réduit la taille finale', 'Docker Compose orchestre plusieurs services', '.dockerignore évite de copier node_modules', 'depends_on gère l\'ordre de démarrage']),
  },

  // KUBERNETES
  { id: 'kubernetes-mod1', courseId: 'kubernetes', title: 'Pods et Deployments', duration: '8h', orderIndex: 1,
    videoUrl: 'https://www.youtube.com/watch?v=X48VuDVv0do',
    theoryContent: `## Kubernetes : Pods et Deployments\n\n### Architecture Kubernetes\n\n- **Control Plane** : API Server, etcd, Scheduler, Controller Manager\n- **Worker Nodes** : kubelet, kube-proxy, container runtime\n- **kubectl** : CLI pour interagir avec le cluster\n\n### Pods\n\nPlus petite unité déployable. Un Pod contient un ou plusieurs containers partageant réseau et stockage.\n\n\`\`\`yaml\napiVersion: v1\nkind: Pod\nmetadata:\n  name: mon-pod\n  labels:\n    app: mon-app\nspec:\n  containers:\n    - name: app\n      image: nginx:1.25\n      ports:\n        - containerPort: 80\n\`\`\`\n\n### Deployments\n\nGère un ensemble de Pods répliqués avec rolling updates :\n\n\`\`\`yaml\napiVersion: apps/v1\nkind: Deployment\nmetadata:\n  name: mon-deploy\nspec:\n  replicas: 3\n  selector:\n    matchLabels:\n      app: mon-app\n  template:\n    metadata:\n      labels:\n        app: mon-app\n    spec:\n      containers:\n        - name: app\n          image: mon-app:v1\n          resources:\n            requests:\n              memory: "128Mi"\n              cpu: "100m"\n            limits:\n              memory: "256Mi"\n              cpu: "500m"\n\`\`\`\n\n### Commandes essentielles\n\n\`\`\`bash\nkubectl apply -f deployment.yaml\nkubectl get pods\nkubectl describe pod mon-pod\nkubectl logs mon-pod\nkubectl scale deploy mon-deploy --replicas=5\nkubectl rollout status deploy/mon-deploy\n\`\`\``,
    practiceContent: `## TP : Déployer sur Kubernetes\n\n### Exercice 1 : Créer un Deployment\n\n\`\`\`bash\nkubectl create deployment nginx --image=nginx:1.25 --replicas=3\nkubectl get pods -w\nkubectl describe deployment nginx\n\`\`\`\n\n### Exercice 2 : Rolling Update\n\n\`\`\`bash\nkubectl set image deployment/nginx nginx=nginx:1.26\nkubectl rollout status deployment/nginx\nkubectl rollout history deployment/nginx\n\`\`\`\n\n### Exercice 3 : Rollback\n\n\`\`\`bash\nkubectl rollout undo deployment/nginx\nkubectl get pods\n\`\`\``,
    keyPoints: JSON.stringify(['Pod = plus petite unité, 1+ containers', 'Deployment gère replicas et rolling updates', 'Labels et selectors pour le lien Deployment→Pods', 'Resources requests/limits pour la QoS', 'kubectl apply -f pour déployer de manière déclarative']),
  },
  { id: 'kubernetes-mod2', courseId: 'kubernetes', title: 'Services et Networking', duration: '8h', orderIndex: 2,
    theoryContent: `## Services et Networking Kubernetes\n\n### Services\n\nUn Service expose un ensemble de Pods via une IP stable :\n\n\`\`\`yaml\napiVersion: v1\nkind: Service\nmetadata:\n  name: mon-service\nspec:\n  type: ClusterIP\n  selector:\n    app: mon-app\n  ports:\n    - port: 80\n      targetPort: 8080\n\`\`\`\n\n### Types de Services\n\n- **ClusterIP** : accessible uniquement dans le cluster\n- **NodePort** : expose sur un port de chaque node (30000-32767)\n- **LoadBalancer** : provisionne un LB cloud externe\n\n### Ingress\n\nRoute le trafic HTTP externe vers les Services :\n\n\`\`\`yaml\napiVersion: networking.k8s.io/v1\nkind: Ingress\nmetadata:\n  name: mon-ingress\nspec:\n  rules:\n    - host: app.example.com\n      http:\n        paths:\n          - path: /\n            pathType: Prefix\n            backend:\n              service:\n                name: mon-service\n                port:\n                  number: 80\n\`\`\`\n\n### ConfigMaps et Secrets\n\n\`\`\`yaml\napiVersion: v1\nkind: ConfigMap\nmetadata:\n  name: app-config\ndata:\n  DB_HOST: "postgres-service"\n  DB_PORT: "5432"\n---\napiVersion: v1\nkind: Secret\nmetadata:\n  name: app-secrets\ntype: Opaque\ndata:\n  DB_PASSWORD: cGFzc3dvcmQ=  # base64\n\`\`\``,
    practiceContent: `## TP : Services et Ingress\n\n### Exercice 1 : Exposer avec un Service\n\n\`\`\`bash\nkubectl expose deployment nginx --port=80 --type=NodePort\nkubectl get svc\n\`\`\`\n\n### Exercice 2 : ConfigMap\n\n\`\`\`bash\nkubectl create configmap app-config --from-literal=ENV=production\nkubectl describe configmap app-config\n\`\`\`\n\n### Exercice 3 : Scaling\n\n\`\`\`bash\nkubectl autoscale deployment nginx --min=2 --max=10 --cpu-percent=80\nkubectl get hpa\n\`\`\``,
    keyPoints: JSON.stringify(['Service = IP stable pour un groupe de Pods', 'ClusterIP (interne), NodePort (node), LoadBalancer (cloud)', 'Ingress route le trafic HTTP via hostname/path', 'ConfigMap pour la config, Secret pour les données sensibles', 'HPA pour l\'auto-scaling basé sur les métriques']),
  },

  // TERRAFORM
  { id: 'terraform-mod1', courseId: 'terraform', title: 'HCL et Providers', duration: '7h', orderIndex: 1,
    theoryContent: `## Terraform : HCL et Providers\n\n### Introduction à Terraform\n\nTerraform est un outil d'Infrastructure as Code (IaC) de HashiCorp. Il permet de décrire l'infrastructure de manière déclarative avec le langage HCL.\n\n### Langage HCL\n\n\`\`\`hcl\n# Variables\nvariable "region" {\n  default = "eu-west-1"\n}\n\n# Provider\nprovider "aws" {\n  region = var.region\n}\n\n# Ressource\nresource "aws_instance" "web" {\n  ami           = "ami-0c55b159cbfafe1f0"\n  instance_type = "t2.micro"\n\n  tags = {\n    Name = "WebServer"\n  }\n}\n\n# Output\noutput "public_ip" {\n  value = aws_instance.web.public_ip\n}\n\`\`\`\n\n### Workflow Terraform\n\n\`\`\`bash\nterraform init      # Télécharge les providers\nterraform plan      # Prévisualise les changements\nterraform apply     # Applique les changements\nterraform destroy   # Supprime l'infrastructure\n\`\`\`\n\n### Providers principaux\n\n- **aws** : Amazon Web Services\n- **azurerm** : Microsoft Azure\n- **google** : Google Cloud Platform\n- **kubernetes** : Cluster K8s\n- **docker** : Containers Docker locaux`,
    practiceContent: `## TP : Premiers pas Terraform\n\n### Exercice 1 : Configuration de base\n\nCréez main.tf :\n\n\`\`\`hcl\nterraform {\n  required_providers {\n    docker = {\n      source = "kreuzwerker/docker"\n    }\n  }\n}\n\nprovider "docker" {}\n\nresource "docker_image" "nginx" {\n  name = "nginx:latest"\n}\n\nresource "docker_container" "web" {\n  image = docker_image.nginx.image_id\n  name  = "web-tf"\n  ports {\n    internal = 80\n    external = 8080\n  }\n}\n\`\`\`\n\n\`\`\`bash\nterraform init\nterraform plan\nterraform apply -auto-approve\nterraform destroy\n\`\`\``,
    keyPoints: JSON.stringify(['HCL = langage déclaratif de HashiCorp', 'init → plan → apply : workflow standard', 'Provider = plugin pour interagir avec un service', 'resource définit l\'infrastructure désirée', 'variable et output pour la paramétrisation']),
  },
  { id: 'terraform-mod2', courseId: 'terraform', title: 'State et Modules', duration: '7h', orderIndex: 2,
    theoryContent: `## Terraform State et Modules\n\n### Le State Terraform\n\nLe fichier terraform.tfstate enregistre l'état réel de l'infrastructure. C'est le lien entre la config HCL et les ressources réelles.\n\n**Remote State** (recommandé en équipe) :\n\n\`\`\`hcl\nterraform {\n  backend "s3" {\n    bucket = "mon-tf-state"\n    key    = "prod/terraform.tfstate"\n    region = "eu-west-1"\n  }\n}\n\`\`\`\n\n### Modules\n\nModules = composants réutilisables :\n\n\`\`\`hcl\nmodule "vpc" {\n  source = "./modules/vpc"\n  \n  cidr_block = "10.0.0.0/16"\n  name       = "production"\n}\n\nmodule "web_server" {\n  source = "./modules/ec2"\n  \n  vpc_id        = module.vpc.vpc_id\n  instance_type = "t3.medium"\n}\n\`\`\`\n\n### Workspaces\n\nGérer plusieurs environnements :\n\n\`\`\`bash\nterraform workspace new staging\nterraform workspace new production\nterraform workspace select staging\nterraform workspace list\n\`\`\`\n\n### Bonnes pratiques\n\n- **Remote state** avec locking (S3 + DynamoDB)\n- **Modules** pour la réutilisation\n- **Variables** fichier tfvars par environnement\n- **State locking** pour éviter les conflits`,
    practiceContent: `## TP : Modules et State\n\n### Exercice 1 : Créer un module\n\nStructure :\n\`\`\`\nmodules/\n  webserver/\n    main.tf\n    variables.tf\n    outputs.tf\n\`\`\`\n\n### Exercice 2 : Workspaces\n\n\`\`\`bash\nterraform workspace new dev\nterraform apply -var-file=dev.tfvars\nterraform workspace new prod\nterraform apply -var-file=prod.tfvars\n\`\`\``,
    keyPoints: JSON.stringify(['State = source de vérité de l\'infra réelle', 'Remote backend (S3) pour le travail en équipe', 'Modules = composants réutilisables', 'Workspaces pour multi-environnement', 'terraform plan avant chaque apply']),
  },

  // ANSIBLE
  { id: 'ansible-mod1', courseId: 'ansible', title: 'Playbooks et Inventories', duration: '6h', orderIndex: 1,
    theoryContent: `## Ansible : Playbooks et Inventories\n\n### Introduction\n\nAnsible est un outil d'automatisation agentless (pas d'agent à installer sur les machines cibles). Il utilise SSH pour se connecter et YAML pour la configuration.\n\n### Inventory\n\nFichier listant les machines gérées :\n\n\`\`\`ini\n[webservers]\nweb1.example.com\nweb2.example.com\n\n[databases]\ndb1.example.com ansible_user=admin\n\n[production:children]\nwebservers\ndatabases\n\`\`\`\n\n### Playbook\n\n\`\`\`yaml\n---\n- name: Configurer les serveurs web\n  hosts: webservers\n  become: yes\n  vars:\n    http_port: 80\n  tasks:\n    - name: Installer Nginx\n      apt:\n        name: nginx\n        state: present\n        update_cache: yes\n\n    - name: Démarrer Nginx\n      service:\n        name: nginx\n        state: started\n        enabled: yes\n\n    - name: Copier la config\n      template:\n        src: nginx.conf.j2\n        dest: /etc/nginx/nginx.conf\n      notify: Restart Nginx\n\n  handlers:\n    - name: Restart Nginx\n      service:\n        name: nginx\n        state: restarted\n\`\`\`\n\n### Commandes Ad-hoc\n\n\`\`\`bash\nansible all -m ping\nansible webservers -m shell -a "uptime"\nansible databases -m apt -a "name=postgresql state=present" --become\n\`\`\``,
    practiceContent: `## TP : Premier Playbook\n\n### Exercice 1 : Inventory\n\nCréez un fichier inventory.ini avec vos serveurs.\n\n### Exercice 2 : Playbook\n\n\`\`\`yaml\n---\n- name: Setup de base\n  hosts: all\n  become: yes\n  tasks:\n    - name: Mise à jour apt\n      apt:\n        update_cache: yes\n    - name: Installer packages\n      apt:\n        name:\n          - vim\n          - curl\n          - git\n        state: present\n\`\`\`\n\n\`\`\`bash\nansible-playbook -i inventory.ini playbook.yml\n\`\`\``,
    keyPoints: JSON.stringify(['Agentless : utilise SSH, pas d\'agent à installer', 'Inventory = liste des hôtes et groupes', 'Playbook = fichier YAML avec les tâches', 'Handlers = tâches déclenchées par notify', 'Idempotence : même résultat à chaque exécution']),
  },
  { id: 'ansible-mod2', courseId: 'ansible', title: 'Roles et Galaxy', duration: '6h', orderIndex: 2,
    theoryContent: `## Ansible : Roles et Galaxy\n\n### Roles\n\nUn role organise le contenu Ansible de manière réutilisable :\n\n\`\`\`\nroles/\n  webserver/\n    tasks/main.yml\n    handlers/main.yml\n    templates/\n    files/\n    vars/main.yml\n    defaults/main.yml\n\`\`\`\n\n### Utiliser un role\n\n\`\`\`yaml\n---\n- name: Déployer l'application\n  hosts: webservers\n  roles:\n    - common\n    - webserver\n    - { role: database, when: "inventory_hostname in groups['databases']" }\n\`\`\`\n\n### Ansible Galaxy\n\nDépôt communautaire de roles :\n\n\`\`\`bash\n# Installer un role\nansible-galaxy install geerlingguy.docker\n\n# Créer un role vide\nansible-galaxy init mon-role\n\n# Requirements file\nansible-galaxy install -r requirements.yml\n\`\`\`\n\n### Ansible Vault\n\nChiffrer les secrets :\n\n\`\`\`bash\nansible-vault create secrets.yml\nansible-vault edit secrets.yml\nansible-playbook site.yml --ask-vault-pass\n\`\`\`\n\n### Bonnes pratiques\n\n- Un role par composant/service\n- Variables dans defaults/ (surchargeables)\n- Vault pour les secrets\n- Tags pour exécution sélective`,
    practiceContent: `## TP : Créer un Role\n\n### Exercice 1\n\n\`\`\`bash\nansible-galaxy init roles/webserver\n\`\`\`\n\nÉditez roles/webserver/tasks/main.yml :\n\n\`\`\`yaml\n---\n- name: Install nginx\n  apt:\n    name: nginx\n    state: present\n- name: Start nginx\n  service:\n    name: nginx\n    state: started\n\`\`\`\n\n### Exercice 2 : Vault\n\n\`\`\`bash\nansible-vault create group_vars/all/vault.yml\n# Ajouter : vault_db_password: supersecret\nansible-playbook site.yml --ask-vault-pass\n\`\`\``,
    keyPoints: JSON.stringify(['Role = unité réutilisable (tasks, handlers, templates)', 'Galaxy = dépôt communautaire de roles', 'Vault pour chiffrer les secrets', 'defaults/main.yml pour les variables par défaut', 'Tags pour exécution sélective des tâches']),
  },

  // GITLAB CI
  { id: 'gitlab-ci-mod1', courseId: 'gitlab-ci', title: 'Pipeline et Configuration YAML', duration: '5h', orderIndex: 1,
    theoryContent: `## GitLab CI : Pipelines\n\n### Le fichier .gitlab-ci.yml\n\nPlacé à la racine du projet, il définit le pipeline CI/CD :\n\n\`\`\`yaml\nstages:\n  - build\n  - test\n  - deploy\n\nvariables:\n  NODE_VERSION: "18"\n\nbuild:\n  stage: build\n  image: node:18\n  script:\n    - npm ci\n    - npm run build\n  artifacts:\n    paths:\n      - dist/\n\ntest:\n  stage: test\n  image: node:18\n  script:\n    - npm ci\n    - npm test\n  coverage: '/Statements.*?(\\d+\\.\\d+)%/'\n\ndeploy_staging:\n  stage: deploy\n  script:\n    - echo "Deploying to staging..."\n  environment:\n    name: staging\n    url: https://staging.example.com\n  only:\n    - develop\n\ndeploy_prod:\n  stage: deploy\n  script:\n    - echo "Deploying to production..."\n  environment:\n    name: production\n  when: manual\n  only:\n    - main\n\`\`\`\n\n### Concepts clés\n\n- **Stages** : phases séquentielles du pipeline\n- **Jobs** : tâches exécutées en parallèle dans un stage\n- **Artifacts** : fichiers produits par un job et transmis au suivant\n- **Variables** : configuration du pipeline\n- **only/except** : conditions d'exécution`,
    practiceContent: `## TP : Premier Pipeline GitLab CI\n\n### Exercice 1 : Pipeline basique\n\nCréez .gitlab-ci.yml :\n\n\`\`\`yaml\nstages:\n  - test\n  - build\n\ntest:\n  stage: test\n  image: node:18\n  script:\n    - npm install\n    - npm test\n\nbuild:\n  stage: build\n  image: node:18\n  script:\n    - npm run build\n  artifacts:\n    paths:\n      - dist/\n\`\`\`\n\n### Exercice 2 : Variables et cache\n\n\`\`\`yaml\ncache:\n  key: $CI_COMMIT_REF_SLUG\n  paths:\n    - node_modules/\n\`\`\``,
    keyPoints: JSON.stringify(['.gitlab-ci.yml à la racine du projet', 'Stages = phases séquentielles', 'Jobs en parallèle dans un même stage', 'Artifacts pour passer des fichiers entre jobs', 'only/except ou rules pour les conditions']),
  },
  { id: 'gitlab-ci-mod2', courseId: 'gitlab-ci', title: 'Runners et Déploiement', duration: '5h', orderIndex: 2,
    theoryContent: `## GitLab CI : Runners et Déploiement\n\n### Runners\n\nUn Runner est l'agent qui exécute les jobs :\n\n- **Shared runners** : fournis par GitLab.com\n- **Group runners** : partagés dans un groupe\n- **Project runners** : dédiés à un projet\n\n### Installation d'un Runner\n\n\`\`\`bash\n# Installation\ncurl -L https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.deb.sh | sudo bash\nsudo apt install gitlab-runner\n\n# Enregistrement\nsudo gitlab-runner register \\\\\n  --url https://gitlab.example.com \\\\\n  --registration-token TOKEN \\\\\n  --executor docker \\\\\n  --docker-image node:18\n\`\`\`\n\n### Environments et Review Apps\n\n\`\`\`yaml\ndeploy_review:\n  stage: deploy\n  script:\n    - deploy-to-review.sh\n  environment:\n    name: review/$CI_COMMIT_REF_NAME\n    url: https://$CI_COMMIT_REF_SLUG.review.example.com\n    on_stop: stop_review\n  only:\n    - merge_requests\n\`\`\`\n\n### Optimisations\n\n\`\`\`yaml\n# Parallélisation\ntest:\n  parallel: 3\n  script: npm test\n\n# DAG (Directed Acyclic Graph)\nbuild_frontend:\n  stage: build\n  needs: []\n  script: npm run build:frontend\n\nbuild_backend:\n  stage: build\n  needs: []\n  script: npm run build:backend\n\`\`\``,
    practiceContent: `## TP : Runner et déploiement\n\n### Exercice 1 : Docker executor\n\nConfiguration avec services :\n\n\`\`\`yaml\ntest_integration:\n  stage: test\n  services:\n    - postgres:15\n    - redis:7\n  variables:\n    POSTGRES_DB: test\n    POSTGRES_PASSWORD: test\n  script:\n    - npm run test:integration\n\`\`\`\n\n### Exercice 2 : Déploiement multi-env\n\n\`\`\`yaml\n.deploy_template:\n  script:\n    - ssh deploy@$SERVER "cd /app && git pull && npm install && pm2 restart all"\n\ndeploy_staging:\n  extends: .deploy_template\n  variables:\n    SERVER: staging.example.com\n  environment: staging\n\`\`\``,
    keyPoints: JSON.stringify(['Runner = agent qui exécute les jobs', 'Docker executor = chaque job dans un container', 'Environments pour tracking des déploiements', 'needs: [] pour paralléliser sans dépendance', 'extends et templates pour le DRY']),
  },

  // GIT AVANCÉ
  { id: 'git-avance-mod1', courseId: 'git-avance', title: 'Rebase et Cherry-pick', duration: '5h', orderIndex: 1,
    theoryContent: `## Git Avancé : Rebase et Cherry-pick\n\n### Rebase\n\nRéapplique vos commits sur une nouvelle base pour un historique linéaire :\n\n\`\`\`bash\n# Rebase simple\ngit checkout feature\ngit rebase main\n\n# Rebase interactif\ngit rebase -i HEAD~3\n# pick, squash, reword, edit, drop\n\`\`\`\n\n### Rebase interactif\n\n\`\`\`\npick abc1234 Ajouter feature X\nsquash def5678 Fix typo dans feature X\nreword ghi9012 Refactoring feature X\n\`\`\`\n\nCommandes disponibles :\n- **pick** : garder le commit tel quel\n- **squash** : fusionner avec le précédent\n- **reword** : modifier le message\n- **edit** : s'arrêter pour modifier\n- **drop** : supprimer le commit\n\n### Cherry-pick\n\nAppliquer un commit spécifique d'une branche sur une autre :\n\n\`\`\`bash\n# Appliquer un commit\ngit cherry-pick abc1234\n\n# Plusieurs commits\ngit cherry-pick abc1234 def5678\n\n# Sans commit (staging only)\ngit cherry-pick --no-commit abc1234\n\`\`\`\n\n### Bisect\n\nTrouver le commit qui a introduit un bug :\n\n\`\`\`bash\ngit bisect start\ngit bisect bad          # le commit actuel est bugué\ngit bisect good v1.0    # v1.0 était OK\n# Git checkout un commit au milieu, tester...\ngit bisect good/bad     # répéter\ngit bisect reset\n\`\`\``,
    practiceContent: `## TP : Rebase et Cherry-pick\n\n### Exercice 1 : Rebase interactif\n\n\`\`\`bash\n# Créer 3 commits de test\necho "a" > file.txt && git add . && git commit -m "commit 1"\necho "b" >> file.txt && git add . && git commit -m "commit 2"\necho "c" >> file.txt && git add . && git commit -m "commit 3"\n\n# Squash les 3 en 1\ngit rebase -i HEAD~3\n# Marquer les 2 derniers en 'squash'\n\`\`\`\n\n### Exercice 2 : Cherry-pick\n\n\`\`\`bash\ngit checkout -b hotfix\necho "fix" > fix.txt && git add . && git commit -m "hotfix"\ngit log --oneline -1  # noter le hash\ngit checkout main\ngit cherry-pick <hash>\n\`\`\``,
    keyPoints: JSON.stringify(['Rebase = historique linéaire, pas de merge commits', 'Rebase -i pour squash, reword, edit, drop', 'Cherry-pick applique un commit spécifique', 'Bisect trouve le commit qui a introduit un bug', 'Ne jamais rebase des commits déjà pushés']),
  },
  { id: 'git-avance-mod2', courseId: 'git-avance', title: 'Hooks et Sous-modules', duration: '5h', orderIndex: 2,
    theoryContent: `## Git Avancé : Hooks et Sous-modules\n\n### Hooks Git\n\nScripts exécutés automatiquement lors d'événements Git :\n\n\`\`\`bash\n# .git/hooks/pre-commit\n#!/bin/sh\nnpm run lint\nif [ $? -ne 0 ]; then\n  echo "Lint failed! Fix errors before committing."\n  exit 1\nfi\n\`\`\`\n\n### Hooks côté client\n\n- **pre-commit** : avant le commit (lint, format)\n- **commit-msg** : valider le message de commit\n- **pre-push** : avant le push (tests)\n- **post-merge** : après un merge (npm install)\n\n### Hooks côté serveur\n\n- **pre-receive** : avant d'accepter un push\n- **post-receive** : après (trigger CI/CD)\n\n### Husky (outil recommandé)\n\n\`\`\`bash\nnpx husky install\nnpx husky add .husky/pre-commit "npm run lint"\nnpx husky add .husky/commit-msg 'npx commitlint --edit $1'\n\`\`\`\n\n### Sous-modules\n\nInclure un repo Git dans un autre :\n\n\`\`\`bash\n# Ajouter un sous-module\ngit submodule add https://github.com/lib/utils.git libs/utils\n\n# Cloner avec sous-modules\ngit clone --recursive <repo>\n\n# Mettre à jour les sous-modules\ngit submodule update --remote\n\`\`\`\n\n### Stratégies de branching\n\n- **Git Flow** : feature, develop, release, hotfix, main\n- **Trunk-based** : main + short-lived feature branches\n- **GitHub Flow** : simple, main + feature branches + PR`,
    practiceContent: `## TP : Hooks et Submodules\n\n### Exercice 1 : Pre-commit hook\n\n\`\`\`bash\nmkdir -p .git/hooks\ncat > .git/hooks/pre-commit << 'EOF'\n#!/bin/sh\necho "Running pre-commit checks..."\nnpm run lint 2>/dev/null || echo "No lint configured"\nEOF\nchmod +x .git/hooks/pre-commit\n\`\`\`\n\n### Exercice 2 : Commit-msg hook\n\n\`\`\`bash\ncat > .git/hooks/commit-msg << 'EOF'\n#!/bin/sh\nif ! grep -qE "^(feat|fix|docs|style|refactor|test|chore):" "$1"; then\n  echo "Message must start with type: feat|fix|docs|style|refactor|test|chore"\n  exit 1\nfi\nEOF\nchmod +x .git/hooks/commit-msg\n\`\`\``,
    keyPoints: JSON.stringify(['Hooks = scripts automatiques sur événements Git', 'pre-commit pour lint/format avant commit', 'Husky simplifie la gestion des hooks', 'Sous-modules pour inclure des repos externes', 'Git Flow vs Trunk-based vs GitHub Flow']),
  },
];
